### ISSUE TITLE
8's instead of bars, cava.psf not loading

### ISSUE THREAD

**Issue by amtino** [karlstav/cava#116]
Similar to Issue #68, I am getting numerals 1-8 in Cava instead of bars, when run from TTY. The bars appear fine from my Raspberry Pi 3's terminal emulator, and via SSH on my MacBook Pro's Terminal. Running latest version of Raspbian. I have cava.psf in my /cava directory but also copied it to ./config/cava for safe measure but still no luck in TTY.

**Comment by amtino** [comment]
Solved: moving cava.psf to user directory (home/pi) makes cava display bars in TTY as expected

**Comment by karlstav** [comment]
@amtino I realize now that this is actually a bug. It will work as long as cava is executed from the same path as cava.psf is located in. The problem is that installing cava to the system `sudo make install cava` should also copy cava.psf to some system font directory. But I have forgotten to implement it.

I'll reopen this, so that I will remember to fix it when I have time.

**Comment by karlstav** [comment]
@amtino if it's still interesting I fount out that copying `cava.psf` to: `/usr/share/consolefonts/` is the actual solution for this issue. At least for debian-based systems. However that path might be different in other distros so I need some kind of distro check to add it to the makefile.
