### ISSUE TITLE
questions about the output

### ISSUE THREAD

**Issue by livibetter** [karlstav/cava#15]
Although it says:

> This program is not intended for scientific use.

But I begin to wonder the output. It all started with #9.

I don't have any tools that can generate test audio, so I generated on my own (see below), an 1kHz, s16le, 2ch, raw PCM audio, `1000hz-s16le-2c-5sec.raw`, using [wave](https://github.com/efferifick/wave):

```sh
% echo $((44100*5)) 1 1000 | wave -r 44100 > 1000hz-f32le-1c-5sec.raw
% # aplay -f FLOAT_LE -r 44100 -c 1 -q 1000hz-f32le-1c-5sec.raw
% ffmpeg -f f32le -acodec pcm_f32le -ac 1 -i 1000hz-f32le-1c-5sec.raw -f s16le -acodec pcm_s16le -filter_complex "[0:a][0:a]amerge=inputs=2[aout]" -map "[aout]" -ac 2 1000hz-s16le-2c-5sec.raw
```

I commented out the parts in db805718e21c7cd8054bcb7b5ab94d9153c29c0a that I think they would be affecting: L568-570 and L595-606. I may miss some, but from the output of ALSA input, I get rid of them enough.

## FIFO
Here is the output of `./cava -i fifo -p 1000hz-s16le-2c-5sec.raw`:

![2015-04-30--11 27 00](https://cloud.githubusercontent.com/assets/30909/7405892/e13238e4-ef2b-11e4-897d-5f9610f32d32.png)

## ALSA
And output of `./cava -i alsa -d pulse` with playback by `aplay -f S16_LE -r 44100 -c 2 -q 1000hz-s16le-2c-5sec.raw` in background:

![2015-04-30--10 30 51](https://cloud.githubusercontent.com/assets/30909/7405426/da7f8440-ef24-11e4-9284-f16526a86647.png)

## Questions

Both peaks did indicate the 1kHz, when I changed the frequency, they shifted, so I believe that does show, but there should not have anything but a peak in FIFO.

* Is FIFO processing correctly?

  Both outputs of inputs should look more or less the same, right? Did I feed in right format of data?

  Below 1k, the leftmost three peaks, there is something interfering, they look related, but I can't tell what it is.

 (Forgot almost everything I learned in signal processing. Sorry, professors!)

* What are the frequency bands, exactly in the output we see?

   The locations of the peaks don't look right at all

  If the output is equally dividing 50-12kHz, 1kHz should be about one 12th of window width from the left. But both are close to the center.

  From what I can see, in `-i alsa`, the rightmost frequency/bar in output is somewhere around 9kHz.

  Is it log scale? 1k almost in middle, 10k almost at right, that sounds about right, doesn't it?

**Comment by karlstav** [comment]
@livibetter let me just say that I really appreciate all the feedback. I had also forgot all i learned in signal processing (it was so hard!), but I re learned some of it when working on cava.


You are absolutely right, there seems to be some "noise" in the fifo processing. I will look through the code, it's over a year since I wrote that part so it might take a while.

Now over to the frequency bands. They are distributed in the same scale as with musical [notes](http://en.wikipedia.org/wiki/Piano_key_frequencies):

```
f=440^(n/12)
```

where n is the number of semitones up or down from a [A4](http://en.wikipedia.org/wiki/A440_%28pitch_standard%29).


In cava the cutoff frequencies are calculated by:

```
fc[n] = 10000 * pow(10, -2.37 + ((((float)n + 1) / ((float)bands + 1)) *
			                                 2.37));
```

So yes, a log scale, per my calculations the middle frequency would be 743Hz. So it looks about right with 1k a bit to the right of the center. I don't remember the details, but as i write in the readme it's supposed to go from 50-12,000Hz

**Comment by livibetter** [comment]
@karlstav Thanks for explanations. I hope you can locate and eliminate those three pesky peaks soon.

**Comment by karlstav** [comment]
turns out i was putting the samples from the temporary read buffer into the shared buffer the wrong way

While the shared buffer contains 2048 samples the temp buffer contains 128 samples. So each of those 128 samples would be inserted backwards. Should be fixde now.
