### ISSUE TITLE
C.A.V.A. on Mac

### ISSUE THREAD

**Issue by trezy** [karlstav/cava#157]
`autogen.sh` and `configure` both run fine after installing `fftw` and `ncurses` with Homebrew and changing `libtoolize` to `glibtoolize` in `autogen.sh`. However, I'm seeing a bunch of errors when I try to run the `make` script. See the output below:

```shell
➜  cava git:(master) ✗ make
Making all in iniparser
make[1]: Nothing to be done for `all'.
gcc -DPACKAGE_NAME=\"cava\" -DPACKAGE_TARNAME=\"cava\" -DPACKAGE_VERSION=\"0.4.2-48-gf76f24d\" -DPACKAGE_STRING=\"cava\ 0.4.2-48-gf76f24d\" -DPACKAGE_BUGREPORT=\"karl@stavestrand.no\" -DPACKAGE_URL=\"\" -DPACKAGE=\"cava\" -DVERSION=\"0.4.2-48-gf76f24d\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_PTHREAD_H=1 -I.  -DPACKAGE=\"cava\" -DVERSION=\"0.4.2-48-gf76f24d\" -D_POSIX_SOURCE -D _POSIX_C_SOURCE=200809L -Iiniparser/src -DPULSE -std=c99 -Wall -Wextra -Wno-unused-result -Wno-maybe-uninitialized  -g -O2 -MT cava-cava.o -MD -MP -MF .deps/cava-cava.Tpo -c -o cava-cava.o `test -f 'cava.c' || echo './'`cava.c
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
In file included from cava.c:37:
./output/terminal_noncurses.c:62:2: warning: implicit declaration of function 'system' is invalid in C99 [-Wimplicit-function-declaration]
        system("setterm -cursor off");
        ^
In file included from cava.c:39:
./output/raw.h:2:63: warning: duplicate 'const' declaration specifier [-Wduplicate-decl-specifier]
        int ascii_range, char bar_delim, char frame_delim, const int const f[200]);
                                                                     ^
In file included from cava.c:40:
./output/raw.c:19:62: warning: duplicate 'const' declaration specifier [-Wduplicate-decl-specifier]
int ascii_range, char bar_delim, char frame_delim, const int const f[200]) {
                                                             ^
In file included from cava.c:44:
./input/fifo.c:55:21: warning: implicitly declaring library function 'abs' with type 'int (int)' [-Wimplicit-function-declaration]
                                if (lo < 0)lo = abs(lo) + 1;
                                                ^
./input/fifo.c:55:21: note: include the header <stdlib.h> or explicitly provide a declaration for 'abs'
In file included from cava.c:54:
In file included from ./input/pulse.c:7:
In file included from /usr/local/include/pulse/pulseaudio.h:39:
In file included from /usr/local/include/pulse/xmalloc.h:24:
/usr/include/stdlib.h:187:6: error: cannot apply asm label to function after its first use
int      system(const char *) __DARWIN_ALIAS_C(system);
         ^                    ~~~~~~~~~~~~~~~~~~~~~~~~
cava.c:567:28: warning: implicit conversion from 'double' to 'int' changes value from 0.125 to 0 [-Wliteral-conversion]
                        if (f[z] < 0.125)f[z] = 0.125;
                                              ~ ^~~~~
cava.c:579:28: warning: implicit conversion from 'double' to 'int' changes value from 0.125 to 0 [-Wliteral-conversion]
                        if (f[z] < 0.125)f[z] = 0.125;
                                              ~ ^~~~~
cava.c:781:20: error: use of undeclared identifier 'FALSE'
        bool reloadConf = FALSE;
                          ^
cava.c:782:18: error: use of undeclared identifier 'TRUE'
        bool senseLow = TRUE;
                        ^
cava.c:919:28: error: use of undeclared identifier 'FALSE'
                bool resizeTerminal = FALSE;
                                      ^
cava.c:937:23: error: use of undeclared identifier 'TRUE'
                                        resizeTerminal = TRUE;
                                                         ^
cava.c:941:23: error: use of undeclared identifier 'TRUE'
                                        resizeTerminal = TRUE;
                                                         ^
cava.c:956:23: error: use of undeclared identifier 'TRUE'
                                        resizeTerminal = TRUE;
                                                         ^
cava.c:961:23: error: use of undeclared identifier 'TRUE'
                                        resizeTerminal = TRUE;
                                                         ^
cava.c:974:18: error: use of undeclared identifier 'TRUE'
                                reloadConf = TRUE;
                                             ^
cava.c:975:22: error: use of undeclared identifier 'TRUE'
                                resizeTerminal = TRUE;
                                                 ^
cava.c:1109:18: error: use of undeclared identifier 'FALSE'
                                                senseLow = FALSE;
                                                           ^
cava.c:1138:36: error: use of undeclared identifier 'TRUE'
                                if (rc == -1) resizeTerminal = TRUE; //terminal has been resized breaking to recalibrating values
                                                               ^
7 warnings and 12 errors generated.
make[1]: *** [cava-cava.o] Error 1
make: *** [all-recursive] Error 1
```

Unfortunately, I don't know anything about C so I haven't the foggiest about what to do next. ☹️

**Comment by karlstav** [comment]
I'm afraid that cava is written for Linux only, It will be quite a job to port it to mac. First of all cava uses alsa or pulseaudio to capture audio, which are linux specific, so that would leave only MPD. 

One idea is to make a portaudio module, then looking at the errors and warnings you got, there is actually not that much work left. But I don't even own a mac so... :confused:

**Comment by trezy** [comment]
@karlstav I'd be happy to work on it and make a PR if you could give me a starting point. I can go ahead and make a branch to update the `autogen.sh` script. The rest of it is what I would need some help with.

I'd also be down to pair for the changes since I have a plethora of Macs. 😁

**Comment by karlstav** [comment]
I don't know what more starting point I could give really... I can try to answer any specific questions, but I don't know how much help I would be as I am not an expert on the differences between Unix/Linux, at least not from a C perspective.

**Comment by trezy** [comment]
@karlstav Any idea on what could be causing these errors?

```shell
error: use of undeclared identifier 'TRUE'
```

I checked and `<stdbool.h>` is definitely available in my `gcc/**/includes` folder, so I'm not sure why it would be throwing that error.

**Comment by chelovechishko** [comment]
Just use lowercase: `true`.

**Comment by trezy** [comment]
Woot! Thanks, @chelovechishko! That takes us from 12 errors to 1!  🎉 😁 🎊

**Comment by trezy** [comment]
@chelovechishko Any insight on this one?

```bash
/usr/include/stdlib.h:187:6: error: cannot apply asm label to function after its first use
int      system(const char *) __DARWIN_ALIAS_C(system);
         ^                    ~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by chelovechishko** [comment]
Sorry, i don't know. I don't know why this part of code (`#ifdef PULSE`) even trying to be compiled. Theoretically, there are `#include "*.c"` (for awkward reason) (unfortunately, `fifo.c` still contains definition of `audio_data` structure), and `output/*.c` files has already used `system()`.

**Comment by pichardoJ** [comment]
I'm getting this same issue with Fedora 26

**Comment by karlstav** [comment]
@pichardoJ you should raise a separate issue. Cava on mac is experimental and not expected to work. But cava works fine on previous versions of fedora. Just create a new issue and post all errors.

**Comment by anko** [comment]
I'm also on Linux, but I got curious, and did some reading. Brief notes on what is necessary for a working Mac port:

Just fixing the compile errors isn't enough, because Cava needs [ALSA](https://en.wikipedia.org/wiki/Advanced_Linux_Sound_Architecture) or [PulseAudio](https://en.wikipedia.org/wiki/PulseAudio) (Linux sound systems) to be present on the system to deliver it an audio stream. OS X doesn't have either. Instead, it has an equivalent API called [CoreAudio](https://en.wikipedia.org/wiki/Core_Audio).

So you could do one of the following:
 - **Make an adapter from CoreAudio to PulseAudio**, then run Cava as though you had PulseAudio.  Maybe you could scrounge something together from [this abandoned adapter project](https://github.com/zonque/PulseAudioOSX) by @zonque? This direction sounds fragile to me.
 - **Write a code path for CoreAudio in cava**. You'd be looking for a way to create a loopback interface on OS X, then read data from that similarly as [cava's existing input methods](https://github.com/karlstav/cava/tree/master/input).

   Some possibly useful reference material if you take this path:

   - [Apple's CoreAudio documentation for developers](https://developer.apple.com/library/content/documentation/MusicAudio/Conceptual/CoreAudioOverview/WhatisCoreAudio/WhatisCoreAudio.html)
   - https://github.com/q-p/SoundPusher
   - https://github.com/akhudek/Soundflower
   - http://www.jackosx.com/

**Comment by karlstav** [comment]
@anko, or perhaps [portaudio](http://www.portaudio.com/). Don't know for sure if it can do what we need, but if it can, it would be perfect.

**Comment by nikp123** [comment]
I got portaudio working [here](https://github.com/nikp123/cava/commit/13adc8ec1ffc97f2ec2a3fc635be6f428d101845).

**Comment by karlstav** [comment]
@nikp123 that sounds awesome, I will check it out soon. Can it capture audio straight from output?

**Comment by nikp123** [comment]
@karlstav But you have to do a one-time configuration, forgot to mention that.
1) Run cava, with portaudio
2) Open pavucontrol
3) Open recording tab (I think)
4) Set cava to record from "monitor"
5) That's it

**Comment by nikp123** [comment]
@karlstav But you have to do a one-time configuration, forgot to mention that.
1) Run cava, with portaudio
2) Open pavucontrol
3) Open recording tab (I think)
4) Set cava to record from "monitor"
5) That's it

**Comment by nicofirst1** [comment]
Is there any update on this?

**Comment by nikp123** [comment]
@nicofirst1 pretty sure my fork can run on macOS flawlessly, I just remember having trouble getting CMake to work
if anyones willing to figure that out that'll be really helpful, since I no longer have a mac machine at home
as for cava itself, I should make a pull request containing just the portaudio code which it needs for audio recording. I'm pretty sure it will build, apart from glibtoolize instead of libtoolize, but you can always check the host OS even though its a messy practice

**Comment by karlstav** [comment]
> I should make a pull request containing just the portaudio code

That would be awesome @nikp123! I have a mac, maybe I can find time to make it work.

**Comment by nikp123** [comment]
I made the changes, you just need to test them.
Also you're going to need a program that routes system audio as a microphone, so this isn't a fully automatic solution, but it gets the job done.

**Comment by karlstav** [comment]
@nikp123, ok so my response time these days is about on month, sorry about that.

I finaly did the merge, it works great, setting `source = auto` it is able to grab my mic, but there are some messages on screen:

```
ALSA lib pcm.c:2564:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
                                                                                                                                      ALSAlibpcm.c:2564:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
                                                                                                                                                                                                                 ALSA lib pcm.c:2564:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)  attempt to connect to server failed
     connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)                                                                                                                                                  attempt to connect to server failed
                                                                                                                                                                                           ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
  ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
 ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused                                                                                                                                                                        ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused                                                             
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
                                                                                                        
```                

sorry about the formatting it was hard to copy because of the way cava manipulates the terminal.

the messages will disappear after a while.

any ideas?
I am running majaro 18.1.1

**Comment by nikp123** [comment]
@karlstav the issue is that portaudio (by default) prints any errors that it finds, these errors may only be suspended on windows by using a preprocessor flag, this however doesn't work on my machine (ArchLinux) so it's not a solution

another way to do this is to use ``close(1);`` which is an POSIX only call that kills stdout, not sure if this will break cava, that's the problem

**Comment by karlstav** [comment]
@nicofirst1 and @nikp123, that was surprisingly easy! took only about half an hour to figure out the quirks

```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install fftw ncurses libtool automake portaudio
export LIBTOOL=`which glibtool`
export LIBTOOLIZE=`which glibtoolize`
ln -s `which glibtoolize` libtoolize
ln -s `which ncurses5.4-config` /usr/local/bin/ncurses5w-config
ln -s /usr/lib/libncurses.dylib /usr/local/lib/libncursesw.dylib
```

however since the virtual terminals in macos is called things like "/dev/ttys001"  cava will always think it runs in a tty (console) and display numbers instead of blocks. Should be an easy fix. I changed the code to force it to run as a virtual terminal and it works as it should. In the standard macos terminal it looks crap, but in iTerm it looks great.

Now we only need a way to loopback audio in portaudio!

**Comment by karlstav** [comment]
was able to make it work with [loopback](https://rogueamoeba.com/loopback/), but I needed your portaudio-list to find the device name @nikp123 strange that there are now better cli tool for portaudio.

**Comment by nikp123** [comment]
@karlstav try [soundflower](https://github.com/akhudek/Soundflower) as its a floss alternative. I used it in my own testing when I used to have a mac

Also you can just #ifdef __APPLE__ for soundflower if the input is set to default

**Comment by karlstav** [comment]
implemented! only took two and half year.
