### ISSUE TITLE
Bars state

### ISSUE THREAD

**Issue by CurseLife** [karlstav/cava#163]
At the beginning im sorry, my english is bad, but i will try to write something about my problem.
I have Arch with ALSA and Alsaequalizer. I changed settings by  your readme to my own and cava works, but with some troubles. When i start Cava, the bars always at that position (link with screen is below), and they moves, but just a little, with little react on music. When playing is stopped, the bars moves anyway at that position, and moves a little. 
https://ibb.co/nD9Pfk
P.S That's a part from config:
method = alsa
source = hw:PCH
That source, because 'Loopback,1' doesn't react and not matter whatever i did.
When i put at source my webcam with microphone (hw:HD4310), it works well, all bars at normal position and react normally!
Many sorry for my language.

**Comment by karlstav** [comment]
Don't worry about the English, my English not perfect either. 

With alsa it is only possible to capture audio from microphone or loopback. From the readme:

Playing the audio through your Loopback interface makes it possible for cava to to capture it, but there will be no sound in your speakers. In order to play audio on the loopback interface and your actual interface you must make use of the ALSA multi channel.

Look at the included example file example_files/etc/asound.conf on how to use the multi channel.

**Comment by CurseLife** [comment]
Hi!
Thanks for the answer!
Problem was solved - I installed pulseaudio and it works well.
Thanks for your product!
<a href="https://ibb.co/h3gDqk"><img src="https://thumb.ibb.co/h3gDqk/2017_05_09_191304_1920x1080_scrot.png" alt="2017_05_09_191304_1920x1080_scrot" border="0"></a>
