### ISSUE TITLE
Slight tearing

### ISSUE THREAD

**Issue by victor-lund** [karlstav/cava#196]
```
pkgname=cava
pkgver=0.6.0
pkgrel=1

```
I am experiencing some random tearing with Cava (it happens once every 10 seconds or so). Not experiencing this with any other application.

Someone have simular issues out there or perhaps know where to look for clues to identify what could be wrong?

**Comment by karlstav** [comment]
what output are you using? ncurses? If so could you check with another terminal emulator.

**Comment by victor-lund** [comment]
I'm not entirely sure, but I assume it uses ncurses (i just installed the package according to instructions). Any way to check this?

To clarify, i installed it like this:
```
trizen -S base-devel fftw ncurses alsa-lib iniparser pulseaudio
trizen -S cava

```
As for terminal emulators, I have tried to run cava with both urxvt and fish with the same exact result.

**Comment by karlstav** [comment]
It should be using ncurses then. Could you elaborate on what you mean by "tearing"? Ncurses is just text on the terminal so it's not clear what it could be.

**Comment by victor-lund** [comment]
It looks just like in this picture - there is this horizontal "tear" (in lack of a better word) that lasts for just a split second but appears regularly. It's not the end of the world, but it is bugging me quite a bit!

![20180227_203009](https://user-images.githubusercontent.com/6714401/36750531-0cf28090-1bfe-11e8-9b51-e253086a63ba.jpg)

**Comment by karlstav** [comment]
I might have seen this before, could you answer the following:

Is it on the clock every 10 seconds or more irregular? 

Is it always the same line or does alter up/down where it appears? 

Does it disappear just as suddenly as it appears or does it move around/gradually fade away.

**Comment by victor-lund** [comment]
1) No, its not every 10 seconds - it's more irregular. Sometimes it happens with just 2 seconds in between, sometimes up to 20 seconds
2) It alters, sometimes it's high up and sometimes low. It seems to be about equally thick every time however.
3) It does not move around or fade - It dissapears instantly.

**Comment by karlstav** [comment]
could you try to run it on legacy non-ncurses mode?

in the config file under `[output]` change this line:
```
; method = ncurses
```

to

```
method = noncurses
```

config file should be located in `$HOME/.config/cava/config`

the colors and performance might be slightly different.

**Comment by victor-lund** [comment]
Interesting!

While using the legacy output method there does not appear to be any tearing! Very nice, but a bit unsatisfying... how come I have issues with ncurses? Any ideas?

**Comment by karlstav** [comment]
No ideas what so ever. But I have the same problem on my Raspberry PI running in the console. Although there the line is sometimes more gradually overwritten instead of suddenly disappearing. So it would be great to figure this one out. 

What version of ncurses are you using?  DE? Could you also check if you have the issue when running directly in the console (tty)?

**Comment by victor-lund** [comment]
Interesting!

Im using:
ncurses 6.1-3
No DE, I'm using a window manager called **i3-gaps 4.14.1-2** (fork of i3-wm).
For compositing i'm using compton v0.1_beta2.5

I tried running cava in the console (tty) and the same tearing occured - a single row dissapearing for a split second. When running with legacy (method=nocurses) there was no tearing.

**Comment by karlstav** [comment]
> I tried running cava in the console (tty) and the same tearing occured

this means that this has nothing to do wit the window manager/DE .

I had this issue on raspbian which still uses ncurses5 also this was a while back with completely different kernel version. What about hardware?

**Comment by victor-lund** [comment]
I see,

Maybe this bug has something to do with my graphics drivers. I use a laptop with "hybrid graphics". This is the info I've been able to gather:

```
lspci |grep VGA
00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)

lspci |grep AMD
01:00.0 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] Mars [Radeon HD 8730M] (rev ff) (prog-if ff)
```
```
glxinfo | grep -i vendor
server glx vendor string: SGI
client glx vendor string: Mesa Project and SGI
    Vendor: Intel Open Source Technology Center (0x8086)
OpenGL vendor string: Intel Open Source Technology Center
```
This hybrid solution has been causing me headache previously. Messing around with drivers in Arch is kind of above my head. However, last time i tinkered with it, i installed amdgpu - wheter it actually works on not, I really don't know.

**Anyway, i doubt this issue has anyhting to do with cava** so feel free to close if you want to. If you're interested with helping me solve my graphic card drivers that's super cool as well of course!

**Comment by karlstav** [comment]
Since I'm having a very similar issue on different HW and different distro and different version of ncurses it would be amazing to get to the bottom of this. 

Ncurses works by first writing to a buffer and then writing to the terminal whenever `refresh()` is called.

So cava writes an entire frame before it is displayed on screen. Can you try to set framerate to 1? To see if the missing line is overwritten in the next frame or if it takes more frames. 

My initial hunch had to do with the buffers not being big enough on the RPI or something. Maybe your "hybrid graphics" share some of the same limitations.

**Comment by victor-lund** [comment]
Interesting!

Using method ncurses, I followed your instructions by setting framerate to 1, but the experiment failed after about 5 seconds: All bars actually "died out" (pushed down to "zero") dispite the fact that I was still playing music. During the few seconds the experiment ran I didnt see any tearing, but I wouldnt say this proves anything.

I tried raising the framerate value to 5, and this is when it gets interesting: I didnt find any tearing at all. I continued to raise the framerate number and found a sweet-spot at around 50, where there is no tearing but performance seems fine.

I'm gonna keep the framerate at 50 for a while to see if the tearing actually has disappeared for good.

Not sure if this helped you, but trying out different framerates appears to work for me.

**Comment by karlstav** [comment]
setting framerate to 1 fails for some reason. 

Good to hear that it's working. Framerate at 50 shouldn't look to different from 60. 

I still have glitchy behavior at framerate 5 and I also have this weird "holes" in the bars that appear after a tear and move around a little before they are written over gradually.

**Comment by victor-lund** [comment]
Hm. It seems like we have different problems (or at least different symptoms) with ncurses. Does your issues also dissappear when you're using the legacy method?

(Do you also use ncurses 6.1?)

**Comment by karlstav** [comment]
yes it disappear with the legacy version. Using ncurses 5.9.

**Comment by enzobarrett** [comment]
How do I change the ncurses framerate?

**Comment by victor-lund** [comment]
@enzobarrett In the config file ~/.conf/cava/conf (depends on your system), simply change framerate like so:

> ; framerate = 60
to
> framerate = 45

**Comment by StevenPolley** [comment]
![2018-04-10-174028_1680x1050_scrot](https://user-images.githubusercontent.com/18017274/38589167-b6297c8c-3ce6-11e8-9839-7b5ee2c51935.png)

I'm also running into this issue.  Lowering my ncurses framerate from 60, even down to 30 does not appear to resolve the issue.

- ncurses-6.1-r2
- rxvt-unicode-9.21
- i3-gaps-git

It happens in TTY as well though.

I'm running this on an i7 860, which is an older processor but should be more than capable of handling this.

From what I gather, the issue lies with ncurses somewhere - or at least behavior has changed in newer versions of ncurses.  

If there's any additional information I can provide, please let me know.

**Comment by benguyer** [comment]
I had a similar issue *only when using tmux* on Linux Mint 18.3 Cinnamon 64-bit. 

* Ncurses version 6.0
* cava-git c3d75c1d9269210f2755be6bb5de84ee8086ba3f
* Cinnamon 3.6.7
* VGA controller: NVIDIA Corporation GK208 [GeForce GT 730] (rev a1)

Adding the lines:

```
[output]
method = nocurses
```

to my (initially empty) config file in ``~/.config/cava/config`` solved the problem. Let me know if there's any further information I can provide.

**Comment by joshuarli** [comment]
Experiencing the same occasional horizontal tear with ncurses. Config:

```
[general]                                                                                           
framerate = 60                                                                                      
autosens = 1                                                                                        
sensitivity = 5                                                                                     
                                                                                                    
[output]                                                                                            
method = ncurses                                                                                    
channels = stereo                                                                                   
                                                                                                    
[smoothing]                                                                                         
integral = 85                                                                                       
monstercat = 1                                                                                      
waves = 1                                                                                           
gravity = 200
```

Decreasing the framerate to 50 solves the issue on my machine. Alternatively, `noncurses` with 60 fps also works for me. Probably just an ncurses or rxvt-unicode issue.

```
$ pacman -Q ncurses cava bspwm rxvt-unicode
ncurses 6.1-6            
cava 0.6.1-1
bspwm 0.9.7-1
rxvt-unicode 9.22-7
```

**Comment by kiikoh** [comment]
**I fixed mine by switching to mono**, I had the same issue, tried the noncurses "solution" above and it actually made it worse it was flickering every other frame.

**Comment by karlstav** [comment]
switching to mono does not help for my issue with tmux

**Comment by MatthewScholefield** [comment]
Just want to mention I also have this problem but it was fixed by using noncurses mode.

**Comment by Xyene** [comment]
Today, while tracking down an unrelated issue in an unrelated project, I think I found _why_ this happens. Unfortunately, I don't think we can do anything about it, because the problem lies in ncurses. 

So... story time.

By default, ncurses buffers up changes made to the screen, and writes out only the difference between the last screen and the current one on a call to [`refresh(3)`](https://linux.die.net/man/3/refresh). [It does this with multiple `write(2)` calls](https://github.com/mirror/ncurses/blob/47d2fb4537d9ad5bb14f4810561a327930ca4280/ncurses/tty/tty_update.c#L987) that change the cursor position.

A terminal can choose to redraw the buffer at any point it wants, _including as ncurses is updating it_. There are no synchronization primitives available*; this is effectively a terminal analog to screen tearing in games and V-sync. If a terminal decides to redraw the screen during an ncurses update, we end up seeing visual glitches.

A program can ask ncurses to not do this diffing, and instead redraw the entire screen, using [`clearok(3)`](https://linux.die.net/man/3/clearok). I tried inserting a call to `clearok(3)` in `cava` right before calling `refresh(3)`, and ncurses [redrew the entire screen _with dozens of calls to `write(2)`_](https://github.com/mirror/ncurses/blob/47d2fb4537d9ad5bb14f4810561a327930ca4280/ncurses/tty/tty_update.c#L1136-L1137) (one per non-empty line). Of course, the flickering was terrible here.

\* [There is a proposal out there](https://gitlab.com/gnachman/iterm2/-/wikis/synchronized-updates-spec?version_id=b50149aa30810ab416d63d9481a28b982940edd0) to standardize these sorts of synchronous updates. This is not quite standardized, and I don't know if any terminal emulators (outside iTerm2?) implement it. Certainly ncurses does not currently send the required control sequence.

**Comment by MatthewScholefield** [comment]
That's what I initially expected. However, why don't I notice any tearing with the noncurses implementation? Ie. If there's some code that makes it work then there should be some patch to ncurses that should make it behave the way as noncurses in cava for similar situations.

**Comment by Xyene** [comment]
The noncurses implementation can still tear (we write it out line-by-line), but I think the probability is lower than when ncurses independently updates everything that might've changed on-screen. noncurses only ever possibly tear near the "tips" of the bars (in particular, in the positive delta between the last frame and the current frame), but those are typically moving so quickly that actually spotting or noticing a tear would be hard.

We also never clear a line before writing it out; ncurses [emits clear-line control sequences in a number of places](https://github.com/mirror/ncurses/blob/47d2fb4537d9ad5bb14f4810561a327930ca4280/ncurses/tty/tty_update.c#L1349-L1353) (all the `ClrToEOL` calls). I believe that's what's being seen [here](https://github.com/karlstav/cava/issues/196#issuecomment-369000445): a terminal which redrew after a clear-line, but before the line was rewritten. I don't claim to have carefully read through that bit of ncurses code, though.

To avoid *all* possibility of tearing, ncurses would need to send out every update in a single call to `write(2)`. I don't think that'd be a simple (or worthwhile) change to ncurses; after all, `cava` is quite a pathological case with 60 FPS updates :)

More support for the synchronous update specification in terminals would be nice to have though, since it would conceivably transparently address this class of issues in a lot of applications.

**Comment by MatthewScholefield** [comment]
Ahh, makes sense. Now I'm wondering if that's the case, why use ncurses for cava at all?

**Comment by Xyene** [comment]
I personally think this behaviour is surprising; it seems to me like the type of thing that isn't obvious until long after you've been bitten by it (as evidenced by this issue being 2 years old).

A case _can_ be made for ncurses, though. For instance, I run ncurses `cava` in a desktop window (similar to [this](https://quantum2.xyz/2019/12/16/desktop-audio-visualizer-i3-cava-wsl/)), and in situations where ncurses _works without tearing_, it uses much less CPU (and therefore battery) than the noncurses backend (which always has to redraw the whole screen).

**Comment by plasmoduck** [comment]
There is a patch made for the 'Simple Terminal' "st" named Autosync which fixes this issue on st. Perhaps you could skim through the source and implement something into cava itself to fix this, if it helps? https://st.suckless.org/patches/sync/ <- The first patch autosync is the one you want.

**Comment by karlstav** [comment]
I am afraid part 1 only can be implemented at the terminal side. The whole problem is that the application (cava or ncurses in our case) have no way of telling the terminal when to draw. Part 2 is interesting because it tries to solve this problem. Will have a look at this as soon as i can.

**Comment by plasmoduck** [comment]
Great, hopefully this can solve this problem once and for all! :)

**Comment by vide0hanz** [comment]
Can confirm this has been resolved in the latest version of `st 0.8.4` which implements the sync patch upstream, you just have to play around with the values in the config.h file

**Comment by akane-sora** [comment]
confirm this problem in cava  0.7.2 with ncurses 6.2.2

**Comment by karlstav** [comment]
the related issues here should be mostly resolved. bottom line is that for some terminals we will require some form of sync. this is now supported for alacritty #453.

**Comment by bdmillan** [comment]
Hi all, I just wanted to say that I experienced the tearing using a RPi 1B with RPi o/s Lite (no DE). Karl, is that how you (or anyone) ran cava on a RPi? I lowered the framerate to 50 > still tearing. Enabled alacritty > still tearing (this was a shot in the dark, since no DE). Changed ncurses to noncurses = **no tearing.** Using: cava 0.8.2-17-g4515856 and ncurses-bin 6.2+20201114-2 armhf (from debian/RPi o/s repos). The monitor is a Kuman 7 inch connected by HDMI with RR=60 Hz. Just wanted to add a data point. I don't suppose there'd be a way to change colors in noncurses from the config file? Thanks for this nice gadget and a great thread. P.S. although I live in NYC, I love Norway and Oslo. Beautiful country.

**Comment by karlstav** [comment]
hi @bdmillan,

that is actually exactly how i originally ran cava and what I first targeted cava for. An RPi 1B back in 2013-2014. I spent a lot of time trying to fix the flickering in ncurses in the linux console (no DE), but to no luck. So that is the whole reason why i developed the noncurses output mode. 

the flickering is not specific to RPi, it behaves like this on any system when running directly in the console. 

in noncurses you are left with the eight predefined colors:

https://github.com/karlstav/cava/blob/a7a9b532f69459be4cb4c956d7b89e823103bdff/example_files/config#L140

there is a typo in the config here, supposed to be eight not seven.

when reading through the Linux console codes [manual](https://man7.org/linux/man-pages/man4/console_codes.4.html) I realize now that i can set 256/24-bit colors! Will start playing with this soon.

**Comment by bdmillan** [comment]
Thanks for that info. It is a really nice program. I took of video of it playing a song with wide stereo separation through a USB ADC on the line out. In case you're interested: https://youtu.be/vo8DdLtlFeE. All the best.

regards,
​Brian ​Millan
________________________________

**Comment by karlstav** [comment]
looks great!

**Comment by bdmillan** [comment]
Hi, all. I just wanted to mention here that I've been away from being able to use cava for some months. I recently got it installed again on my RPi 1B. I used the Raspbian package which is currently version 0.7.3-1. (Had some errors building from source r/t pipewire I think, but that's for another thread if I can't sort it).
I have again noticed the "tearing" in ncurses mode that we've seen before. However, I also noticed that once cava is running and settled down, if I reload the configuration while it's running a couple of times the tearing problem is significantly better. I never really tried doing that because I only ever ran it in noncurses mode which doesn't have the option 'r'. Tearing not gone, but a definite improvement for me. As usual, thanks for this nice piece of work!
