### ISSUE TITLE
Adopt a Source Style

### ISSUE THREAD

**Issue by winny-** [karlstav/cava#210]
It appears some of the source files have mixed tabs & spaces, and inconsistent style. What C style does this project use?

**Comment by ginkage** [comment]
According to CONTRIBUTING.md, it's supposed to be "tab for indents; curly braces on same line as if, while, for statements".
I agree that this project could use some clang-format treatment.

**Comment by karlstav** [comment]
I used to use something called astyle to style it automatically, but then I was advised not to use automatic styling and just be more consistent when writing the code.

Since then I guess it has slipped out a bit.

This is on the todo-list, since my time is limited at the moment please feel free to contribute!

**Comment by antiprism** [comment]
I have been using clang-format for a project, and I find it makes life very easy. I don't enforce the style for contributions, but just apply it to all the code from time to time. It is possible to exclude blocks, e.g. preformatted help text, from being reformatted.

https://clang.llvm.org/docs/ClangFormat.html

**Comment by quantum5** [comment]
`clang-format` has been adopted in #292.
