### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by kxygk** [karlstav/cava#214]
Just a friendly note. The licensing is a bit confusing (maybe wrong?). FFTW is GPL'd - so the final package can't be MIT licensed

https://www.quora.com/If-I-use-GPL-code-will-I-be-able-to-redistribute-it-with-an-MIT-license?share=1

(just saw your repo randomly and had this FFTW/GPL issue before myself :) )

**Comment by geokon-gh** [comment]
I don't think linking is relevant in this case b/c it's not licensed under the LGPL. I'm not an expert either but my understanding is that just like if cava were closed source, you can't use FFTW under a different license.

**Comment by antiprism** [comment]
My understanding is that the MIT licence is compatible with GPL, and so Cava binaries can be built against a GPL licensed library, but the resulting binary is covered by the GPL license rather than the MIT licence
https://www.gnu.org/licenses/gpl-faq.html#WhatDoesCompatMean

I don't think there is any problem with the Cava project using the MIT license exclusively if it is not distributing binaries.

**Comment by karlstav** [comment]
I don't have a problem with changing it to gpl, but MIT is just much simpler. Also I don't know if there is any measures that must be taken to change the license at this stage.
