### ISSUE TITLE
couldn't open rec stream: No such file or directory input/sndio.c: Could not open sndio source: default

### ISSUE THREAD

**Issue by amarahjiwa** [karlstav/cava#221]
I'm currently running cava on my raspberry pi 2 model B.
How I install, is by typing this commands. 

```
sudo apt-get install libfftw3-dev libasound2-dev libncursesw5-dev libpulse-dev libtool
git clone https://github.com/karlstav/cava.git
cd ./cava/
sudo ./autogen.sh
sudo ./configure
sudo make
```
and when I run the program, I got this error message.
```
couldn't open rec stream: No such file or directory
input/sndio.c: Could not open sndio source: default
```

**Comment by karlstav** [comment]
@amarahjiwa cava defaults to sndio if it is installed (and apparently it is). I am guessing that you want to use pulseaudio insdead. Go to the cava config file in `~/.config/cava/config` and uncomment this line

```
method = pulse
```

I realize now that sndio is not well documented and also pulseaudio should be default anyway since it says so in the readme.

**Comment by amarahjiwa** [comment]
Thank you so much. The program now works like a charm.

**Comment by Amit0617** [comment]
For me, somehow `cava` worked once but didn't work next time, throwing same error as mentioned above. Since, I have seen the behaviour of `cava` using `sndio` also. One important difference is that when nothing is playing on system, `cava` was showing output of microphone through graphs. So, `pulseaudio` isn't replacement of `sndio`.
