### ISSUE TITLE
Audio buffer overrun and latency issues

### ISSUE THREAD

**Issue by jarcode-foss** [karlstav/cava#241]
(This is a courtesy bug report from [glava](https://github.com/wacossusca34/glava), which currently shares a good deal of the PulseAudio input code from `input/pulse.c`)

It's possible to encounter output issues (dropped fragments resulting in broken audio data) due to hardware input overrunning PulseAudio's audio buffer. A simple fix would be to set the `maxlength` member in `pa_buffer_attr` to `(uint32_t) -1` in order for the server to select an appropriate buffer size.

In the same vein, it's possible to encounter some fairly serious latency issues depending on the output device. This is because the requested fragment size doesn't actually affect how PulseAudio samples from the underlying hardware, only the server's (intermediate) buffer.

While it's possible to work around this by using a null sink instead, an ideal solution would be to use `pa_stream_connect_record`'s `pa_stream_flags_t` flags argument to specify `PA_STREAM_ADJUST_LATENCY`. Unfortunately the `pa_simple` API doesn't expose this.

**Comment by karlstav** [comment]
thanks for the report @wacossusca34 , I was actually planning to make an OpenGL output module for cava some day. But have not gotten around to it yet. 

I will definitely take a look at the `pa_buffer_attr`fix.  Any idea how common these buffer overruns are? And are the effects on the visualisation easily noticeable?

Have you made any efforts towards using the Asynchronous API? For me it looks just too complex for this type of application.

**Comment by wacossusca34** [comment]
@karlstav In the case of Cava, artifacting is not immediately present due to the buffer size for FFT computations is the same as the audio fragment size. Visualization simply will skip the truncated channels. In the event of artifacts filling a circle buffer, in the event of GLava, the wave will be broken and there would be significant noise resulting from the FFT computation on the upper end of the spectrum, which is how I discovered the bug.

Buffer overruns can be common on certain hardware. It depends on how pulseaudio internally samples from the hardware into its internal buffer, which is not controllable via the `pa_simple` API.

> Have you made any efforts towards using the Asynchronous API? For me it looks just too complex for this type of application.

I will be rewriting my PA backend with the async API when I have time and you are free to incorporate the code, although be aware of the license differences.

> I was actually planning to make an OpenGL output module for cava some day.

OpenGL has a range of visualization possibilities and I believe the way GLava exposes this is sufficient, compared to simply providing a bar graph visualizer in Cava.
