### ISSUE TITLE
CAVA causes audio popping

### ISSUE THREAD

**Issue by farzads2** [karlstav/cava#258]
Hi,
After running CAVA, whenever I change volume slider in any applications, sound pops and crackles.
This is output of `pacmd list-sinks ` and `pacmd list-sources` :
https://pastebin.com/d468baTR
https://pastebin.com/QZiwqvRV

**Comment by karlstav** [comment]
hi @farzads2 

Not able to reproduce, but I have had similar issues on the first raspberry pi when using pulseaudio (even without cava or sliding volume), this was caused by the fact that pulseaudio needs some cpu to run smoothly. I can see that sliding audio in any application causes high CPU usage. Size of terminal window and what terminal software running cava also affect CPU. Output of `top` would be interesting.

Have you pulled the latest cava? Commit ce9910d reduced cpu usage pf pulseaudio significantly. 

There is also [this](https://wiki.archlinux.org/index.php/PulseAudio/Troubleshooting#Pops_when_starting_and_stopping_playback).

**Comment by farzads2** [comment]
Well, I'm using a desktop PC with i7 2600k CPU, so i doubt this is because CPU usage.
But I checked latest version anyway and the issue persists.
I also tried the solutions on arch wiki before posting here, none worked.
This is probably specific to my PC or my sound card, if you can't reproduce it.
Another thing is if I use pulseaudio equalizer, it also causes latency on sound and audio starts popping.
Thanks anyway.

**Comment by karlstav** [comment]
sounds like more of a pulseaudio issue then, [this](https://www.reddit.com/r/linux4noobs/comments/5twums/audio_distortioncrackling_when_changing_volume/) looks like the same issue.
