### ISSUE TITLE
Split into a "cavalib" library for use in other applications?

### ISSUE THREAD

**Issue by k80w** [karlstav/cava#260]
Since Cava itself does a good deal of processing to make pretty spectrums, it'd be great to be able to more easily use this in other applications that want to display spectrums.

Currently this is possible by using the raw data from the `raw` output mode, but using standard streams can cause issues with buffering, and using Cava from the command-line requires you to create a config file to use it, meaning any application wanting to use Cava would have to manage the lifetime of whatever config files it creates.

Making Cava compilable into a library that can be loaded by other applications would make developing around it less tedious and feel a little more "static."

**Comment by karlstav** [comment]
I have no experiencing with writing a library but I wouldn't mind the learning experience. There is however some things to consider. Cava already relies on the [fftw](http://www.fftw.org/) library to do the Fast Fourier Transformation which is what makes a spectrum analysis possible. So maybe there is no need for a separate "cavalib". However, Fourier transformations are abstract mathematical operations giving out complex values that can be hard to put in use. So maybe the cavalib could act as a wrapper around `fftw` making it easier to use for audio visualization. 

What would you propose be the functions to provide? I am thinking a long the lines of something similar to fftw with a `init(input, output)` function, where `input` is the alsa input device, pulseaudio source or fifo file. The `output`could be the same as the `raw` output. And then there would be a simple `execute()`function.

The question would be how configurable to make it. Length of audio buffers, number of output values, range etc.. any ideas?

**Comment by dnaf** [comment]
I think Cava does enough processing of its own to be worth having its own library; features like the "monstercat" smoothing make Cava much more useful and easier to use than a pure FFT lib. There are many cases where a developer just wants a pretty spectrum visualization in their application without having to think about how to implement smoothing, sensitivity adjustment, etc.

I'm not entirely sure about how the API would work, but I *would* say that rather than having an `init(input, output)` and `execute()`, I think it should be closer to `input(bars, buffersize, more options, etc)` and `execute(input, output)` where `input` is an array of samples from the audio buffer provided by the user and `output` is an array of bars.

Personally, I think that the library shouldn't handle any audio devices directly. Using a buffer provided by the user would make the library more "universal" and adaptable. This would also have the added bonus of making the library easier to port to other platforms, if that were ever a goal, as it wouldn't be dependent on the target system's audio system.

In terms of configurability, I think just about everything in the `[general]` and `[smoothing]` sections of the config file would be necessary inputs for the library to accept. On top of this, it could be nice for the library to allow you to specify more advanced options, such as FFT accuracy. This may be unnecessary.

**Comment by iamsubhranil** [comment]
probably unrelated, but although I may not want a separate 'cavalib', I would probably consider modularising the code much more. In it's present state, the core 'cava.c' depends on a whole lot of global variables from other '.c' files and instead of only communicating through the header defined interfaces, mixes up and uses everything from everywhere, resulting in a tough project to edit, modify and extend for new people (which I learned at the time of #230 )

**Comment by nikp123** [comment]
@iamsubhranil I approve of making it separate (I'll try it myself because I'm familiar enough with the code), maintaining a fork like this is slow and annoying. Not forcing or suggesting anyone to waste their time trying to make it separate, but it would really speed up development.

Also I'm considering refactoring my repo because it's slowly turning into a unmaintainable mess. (git cherry-picking isn't fun)

If I find time I'll try making it (without my own modifications first)

**Comment by karlstav** [comment]
I agree that the code could be more modular and better structured. I hope to getting around to doing that at some point, but can't really promise anything at the moment.

@nikp123 you touch a very interesting issue about the FFT! Cava is no good at very low frequencies because it uses a sample size of 2028, with one FFT you can't detect lower frequencies than:

 `1 / (sample size / sample rate) * 2`.  

That makes 

`1 / (2048 / 44100) × 2 = 43 Hz` 

in most cases, which I though would be enough. But maybe increasing the sample size could be an idea. In that case we must increase the global variable `M` and some parameters in all the input files, and maybe some more stuff... (with better structured code, this could have been a config option)

**Comment by nikp123** [comment]
also i just wanted to add that by splitting the "main" code into a library you could achieve unit tests more easily: https://github.com/karlstav/cava/issues/21 and practically kill two bird but with a rather heavy stone (because it requires the refactoring of the entire codebase and more)

**Comment by karlstav** [comment]
this is how a Imagine it could be done:

* *cavalib* (act as a sort of wrapper for FFTW, takes a buffer of audio as input and gives a array of bar heights as output.) might use a planner function with config and an execute function to go in the loop, just as [fftw does](http://www.fftw.org/fftw3_doc/Complex-One_002dDimensional-DFTs.html#Complex-One_002dDimensional-DFTs)
* *cava inputlibs* (pulse,alsa,fifo,sndio...), must be optional to use/compile as people might want to use the cavalib within other applications.  Need an init function and then a read function that goes in the loop. Today the audio inputs are threaded, but I don't really think that is necessary.
* the output modules would be baked into the *cava application* with the libs described above and work the same way as today. This can be used as it is or just as an example application on how to use the cavalib

this way we can keep the cava application in the center of things, other modules can be written very easily either to be used with the cava application or to be used with cavalib in other applications. Git sub-modules might be considered, but I don't think it's necessary to split things like that. CMake might also be considered to make modularization the building easier.

**Comment by nikp123** [comment]
Let me add two more cents on top of what you suggested:

Firstly cavalib sounds like a good idea, but one of the options I also came up with that might not be compatible with cavalib is to treat individual filters (such as gravity, monstercat and so on) as seperate modules, where the developer who would want the features of cava would have to import all of the individual filters into their project as opposed to a simple library. This is a disadvantage for the app developer, however it would make adding filters THAT easier. However this is just an idea I had, and probably a pretty dumb one. But still, an idea.

As for the inputlib and outputlibs, they should have access to all of the variables (exposed by struct) AND also should be able to read the config file themselves. 

Why? Because some features of inputs and outputs cannot be just described through already known parameters defined within CAVA. The example I have shown in #402 demonstrates that. 

Just to repeat that example: Let's say you want to add some complicated gradient or shader to an output, instead of adding that paramater to the core CAVA engine, instead you could have the module itself doing the heavy-lifting because IT'S responsible for adding that parameters. 

This should REALLY help with reducing code complexity and improving overall maintenance. One other benefit of having the I/Olib read config file is it's ability to prevent bugs and quirks specific to that output without, again, tainting the core CAVA code.

As for CAVA inputlibs, keep them threaded as it avoids buffer misses whereby CAVA would miss some of the incoming audio due to it being late to receive it. It's actually good design IMO. 

Ignoring that, I've did my own inputlibs just like you've described: Where the two functions are exposed: ``xavaInputHandleConfiguration`` and ``xavaInput`` (example done in [FIFO here](https://github.com/nikp123/xava/blob/unstable/src/input/fifo/main.c))

As for the outputs, you can freely adopt the design I went with (example in [SDL2](https://github.com/nikp123/xava/blob/unstable/src/output/graphical_sdl2/main.c)):

Ordered by execution, they are:
```
xavaOutputHandleConfiguraion - This function would be responsible for loading in any output related features through the config file and resolving and output-related quirks and bugs such as Vsync not being supported in SDL2 (in this case)
xavaInitOutput - Handles initial output related setup at startup
xavaOutputApply - Where any mid-execution changes are applied. In cases of CAVA, that would be adjusting the output once the terminal had been resized
xavaOutputHandleInput - The obvious
xavaOutputDraw - A function that would be responsible for drawing a single frame of the output
xavaOutputClear - This function is responsible for clearing the outputs screen when the output has reached an "unsafe" state to continue with it's old buffer or in case of handling external changes (similar to xavaOutputApply, but NOT the same)
xavaOutputCleanup - Handles cleaning up any resources when the program is closing
```

One thing that is still unclear is how the structs that are shared between the CAVA core engine and the input/outputlibs should look like and what should they contain.

One idea I fully support is to move as much things as possible to structs as to avoid the ugliness that is the ``xavaOutputDraw`` function.

Anyway any suggestions and feedback are helpful

**Comment by nikp123** [comment]
Oh yeah, let's not forget execution states, where all useful variables (that aren't config related) are shared between CAVA and it's modules in the same struct fashion described above.

**Comment by nikp123** [comment]
Update: Kinda implemented this with "filters" (because they filter audio)

See here: https://github.com/nikp123/xava/tree/unstable/src/filters/default

Documentation doesn't exist yet, but essentially these functions alone (provided you call them in order and give them valid data) produce the output of my visualizer completely on its own. I could possibly even port the "original" cava engine into this since xava has a few differences (let me know).

**Comment by karlstav** [comment]
looks interesting, haven't have time to look deeply into this yet. but i have gotten some feedback that indicates that this could be useful.

**Comment by chincheta0815** [comment]
Hej there,

maybe this repo here helps:https://github.com/chincheta0815/LMS-to-Hue/commit/5ba86894666fed31a4032e594eddf3c12f979a1c

I also tried to extract some cava functions to use them in another project that should be integrated in a squeezelite instance (w/o shm) and make lights flash.

I hope that inspires you and maybe someone can give me a hint why it is not working correctly...
