### ISSUE TITLE
When terminal width is small (read: tiny) floating point exception happens

### ISSUE THREAD

**Issue by sjef** [karlstav/cava#32]
Using `urxvt` with the smallest width allowed, the program crashes and gives off this error:
`floating point exception (core dump)`.

**Comment by karlstav** [comment]
is it like unuasble small? How many collumns? Maybe cava should just quit and throw an error when the terminal is to small? Or wait until the terminal window is resized.

**Comment by sjef** [comment]
It's one character wide, whatever that is. I'm sure you can replicate it using urxvt and the default configs. I've included a picture demonstrating how small it is.

![capture](https://cloud.githubusercontent.com/assets/8290704/7701488/e714ad18-fe27-11e4-9636-bcd930dd8d06.PNG)

**Comment by anko** [comment]
[i3wm](https://i3wm.org/) doesn't even let me resize that small! :smile:

Maybe from [`i % bw` here](https://github.com/karlstav/cava/blob/1d5bd3cab947c26794388fe0b8a118ee9e48c960/cava.c#L687), if `bw == 0` due to [integer division here](https://github.com/karlstav/cava/blob/1d5bd3cab947c26794388fe0b8a118ee9e48c960/cava.c#L482)?

**Comment by karlstav** [comment]
It's probably beacuse of [this](https://github.com/karlstav/cava/blob/1d5bd3cab947c26794388fe0b8a118ee9e48c960/cava.c#L468), it sets the number of bars to -1 :frowning: if the terminal is one chrachter wide. will fix

**Comment by karlstav** [comment]
hmm so "fixing" is not one of the magic words that automatically closes the issue. I could have used fix, fixes or fixed, but no not fixing, close but not close enough for closing. Anyway it's fixed, however having only one bar produces no action because of the monstercat smoothing. One would have to use scientific mode. But who would want to have only one bar anyway...
