### ISSUE TITLE
Windows build / switch to PortAudio

### ISSUE THREAD

**Issue by CelestialWalrus** [karlstav/cava#34]
Well, I was thinking about porting cava to Windows & OS X, and I think a switch to PortAudio would be great, because it solves some of the issues.

Also: I think you can use PortAudio on Android, so that'd be nice.

> PortAudio is a free, cross-platform, open-source, audio I/O library.  It lets you write simple audio programs in 'C' or C++ that will compile and run on many platforms including Windows, Macintosh OS X, and Unix (OSS/ALSA).

**Comment by anko** [comment]
Observations:

-   Windows [has no ncurses][1]—the console rendering library we'd [like to use][2].
-   Cross-platform support without automated tests (#21) is painful.
-   Since rendering likely differs most between OSs, having the code calculating bar heights separated from rendering (#24) would help.

I think those are prerequisites for a Windows / OSX port.

If the bar calculation code were extracted to a “libcava” library, it would likely be easiest to treat “Linux cava”, “Windows cava”, *et cetera* as separate projects, as they'd share very little code.

[1]: http://stackoverflow.com/questions/14779486/curses-alternative-for-windows?lq=1
[2]: https://github.com/karlstav/cava/tree/ncurses

**Comment by CelestialWalrus** [comment]
> Windows has no ncurses—the console rendering library we'd like to use.
We could go with cygwin, which supports ncurses. You can distribute it with cygwin's dll to make cava standalone.

> Since rendering likely differs most between OSs, having the code calculating bar heights separated from rendering (#24) would help.
Framebuffer graphics would be great.

The biggest issue is that the code is so painfully nonmodular (i.e. the "shared" variable, which makes everything hard). I've tried to separate different parts (i.e. move input_alsa -> input/alsa.c; input_fifo -> input/fifo.c; drawing -> output/terminal.c; etc.), but I wasn't able to do it.

**Comment by karlstav** [comment]
Sounds possible. I think it would help if we where able to separate cava in to three different "parts" first:

 - Audio extraction (separate: portaudio, fifo, alsa...)
 - Bar calculation (shared)
 - rendering (separate: ncurses, printf...)

(@CelestialWalrus I was just writing this when you commented. ) 

The shared variable is, I admit, not ideal... I needed a way to pass the audio from the audio thread to the main thread. Any other way of doing this?

**Comment by CelestialWalrus** [comment]
@karlstav maybe pointers, but I'm not sure if those work with pthread. Or execute the input_* function in realtime (i.e. `while (whatever = input_alsa(args))`).

I'd like to suggest a directory structure if you don't mind:

    |
    |- input
       | alsa.c/alsa.h
       | fifo.c/fifo.h
    |- output
       | terminal.c/terminal.h
    | cava.c
    | Makefile

(...and that autoconfigure thing, but I'm not sure how to exactly use it)

**Comment by karlstav** [comment]
Looks good. 

If you're thinking about executing the alsa input audio as a function, not a thread, every time cava is supposed to listen to audio. I already tried it en early early development. It didn't work very well as I missed huge chunks of the audio.

Pointers might work, I think I tried that as well, but because I suck at pointers I got nowhere.

**Comment by nikp123** [comment]
Ironically enough I made a "working" [WIN32 renderer](https://www.dropbox.com/s/fzhkcg923yu7fh7/cava.7z?dl=0) (which compiles only under cygwin for now) only to find this. Would like to switch to a non-Pulseaudio/ALSA thing to make this actually usable.

**Comment by karlstav** [comment]
@nikp123 portaudio is the thing then. I don't think the implementation would be so difficult now, as the problems disused in this thread have been solved.

One question that remains is how to capture audio from application or output in portaudio.

**Comment by nikp123** [comment]
@karlstav [someone already asked that question](https://stackoverflow.com/questions/15690668/continuous-recording-in-portaudio-from-mic-or-output), but I'm not sure how accurate are the results that the guy got.

**Comment by nikp123** [comment]
@karlstav [This](https://github.com/nikp123/cava/commit/7f075f6fe58fcba2e8472400a3e6c903bb090cb9) and [this](https://github.com/nikp123/cava/commit/13adc8ec1ffc97f2ec2a3fc635be6f428d101845) commit may be of interest. 
^I made the darn this, YAY!
