### ISSUE TITLE
Bar height is not proportional to terminal height.

### ISSUE THREAD

**Issue by mkrasnitski** [karlstav/cava#351]
Depending on the height of your window, the maximum bar height achieved by cava takes up a larger proportion of the total height, instead of scaling linearly. Unless this is intended, I feel it would be more intuitive to have it scale linearly. [Here's](https://gfycat.com/bewitchednewbee) an example video of what I'm talking about, and [here's](https://termbin.com/gb1x) my current config.

**Comment by karlstav** [comment]
it is most likely due to the calculations done here:

https://github.com/karlstav/cava/blob/a0ab48bddcafdd1744bd85ecf7fe8ca3a81af564/cava.c#L634

or it  looks also look like what I was trying to solve in those calculations. I am not very pleased with that solution, but I just could not get the math right.

what versjon of cava are you on?

**Comment by mkrasnitski** [comment]
```
 ❯ cava -v
cava 0.6.1-173-g7ce8845
```

**Comment by karlstav** [comment]
yes, I tried to improve upon this here: 7d10ab5b75a5e94d8e8022fe94e35cbd96de4954

if you pull the latest version it is a little better.

The problem is that the increase in height affects the integral filter in a non-linear matter:

https://github.com/karlstav/cava/blob/a0ab48bddcafdd1744bd85ecf7fe8ca3a81af564/cava.c#L936

However, my mathematical skills are just not good enough to provide a perfect solution.

**Comment by karlstav** [comment]
@mkrasnitski did you test the latest version, does it seem better?

**Comment by mkrasnitski** [comment]
Trying it out on the latest version, It seems that the scaling is now almost logarithmic. Going from short to medium height, it's pretty close, but with a full size window, the height stays almost the same. The one thing I do notice is that there is less smoothing with the larger window, meaning the bars are pretty jumpy. Here's a video of what I'm talking about: https://www.youtube.com/watch?v=UQOzXygIhZM

**Comment by mkrasnitski** [comment]
I'd be happy to help out with the mathematics. I'm not too familiar with every transformation you're doing, so I'm not what what effects certain values should have (i.e. the smoothing integral, gravity, etc.). I know there's a fourier transform somewhere obviously, but are all the transforms done on top of that by assuming it's done correctly? In that case, if it's just some integrals I could help out, since I haven't worked much with FTs before.

**Comment by karlstav** [comment]
sorry about the late reply! the integral filter is as simple as doing a:
`bar_value = previous_bar_value * some_factor + bar_value` where the factor is calculated out of the integral config parameter. 


What it looks like is that this factor must be reduces with height, but it looks like I might be reducing it to much:

https://github.com/karlstav/cava/blob/a0ab48bddcafdd1744bd85ecf7fe8ca3a81af564/cava.c#L634

The more that factor is reduced the less integral filter and the more jumpiness.

There is obviously room for improvement here, but there are a lot of other factors also that could be causing this, like the gravity thing. I have to dig some more, will look at it when I get more time.

BTW do you have autosens switched off? How does it look if you switch it on?
