### ISSUE TITLE
Ncurses build is "slower" in urxvt.

### ISSUE THREAD

**Issue by CelestialWalrus** [karlstav/cava#36]
It seems less responsive for me.

**Comment by karlstav** [comment]
this might be. I changed the order of the three diferent filters from:

* falloff
* integral
* monstercat

to:

* falloff
* monstercat
* integral

Thought it looked better, but maybe I was wrong. I'll do some more testing with different orders. Decreasing the constant used in the integral (now 0.55) should also make it more snappier. 

Or is it just in urxvt? Then it might be something with ncurses ans this particular terminal emulator.

**Comment by CelestialWalrus** [comment]
@karlstav I think it's only urxvt's problem.

**Comment by rolf1304** [comment]
Same issue here with URxvt and xterm. Both also have flickering rows now, and no "no-background" mode, with this error:
  setterm: terminal rxvt-unicode-256color does not support --blank
Also, URxvt now displays flickering cursors at the bars' tops.
LXTerminal has the same issues except for the flickering.

**Comment by karlstav** [comment]
this is strange, responsiveness in my urxvt is indistinguishable from gnome-terminal, when running normal size window. When maximized urxvt is actually slightly better. I have tested both 8 and 256 color versions.

Also I'm having no problem with not setting background in Lxterminal. Neither xterm nor uxterm outputs anything though...

My ncruses version is 5.9.20140118

rxvt-unicode (urxvt) v9.19 - released: 2013-10-27

lxterminal -version: XTerm(297)

There might however be some cleaning up to do in the code after moving to ncurses. Some of the terminal preparations might be superfluous.

**Comment by CelestialWalrus** [comment]
@karlstav It happens in Terminator now and IDK why.

http://gfycat.com/AnimatedInexperiencedAnnelida
http://gfycat.com/ShadyForcefulDrongo

cava.sh: `cava -i fifo -p /tmp/mpd.fifo -f 70 -b 60`

**Comment by karlstav** [comment]
My terminator looks just fine, except I have the good old horizontal lines, caused by character spacing (referenced to in issue #6).

I think our different results might be font related. Have you tried using different fonts? What font are you using?

**Comment by CelestialWalrus** [comment]
@karlstav The problem is not with horizontal bars, but with general slowness. Compare ncurses to older ones.

**Comment by karlstav** [comment]
What I meant was that the issue illustrated [here](http://gfycat.com/ShadyForcefulDrongo)  and also the issue described by @rolf1304 as "flickering cursors at the bars' tops", might be font related. I will open a separate issue to avoid further confusion.

**Comment by CelestialWalrus** [comment]
@karlstav I've made a fork without ncurses. CelestialWalrus/cava-nocurses

**Comment by karlstav** [comment]
@CelestialWalrus I made a separate branch before merging ncurses into the main branch:

https://github.com/karlstav/cava/tree/printf-version

maybe I should have named it differently

**Comment by karlstav** [comment]
@CelestialWalrus after comparing the printf version with ncurses I can see that the ncurses version is indeed much slower. But it is not only in urxvt! I'm not 100% sure why, it might be related to the filters now being executed more successively after the extraction of the values, thus taking longer time.

Anyway I discovered that my "integral filter" should be:
```
fmem[o] = fmem[o] * 0.55 + f[o];
f[o] = fmem[o];
```

not:
```
fmem[o] += f[o];
fmem[o] = fmem[o] * 0.55;
f[o] = fmem[o]; 
```

as it had been. The idea of this filter is to keep part of the last values in the current value, thus smoothing out sudden changes. (I think this type of filter has a more scientific name which I have forgotten). The error in the previous one was that it used 55% of the last value and the current. No it uses 55% of the last and 100% of the current.

However I think the reason why I didn't do anything about it was that I kind of like it slow (maybe because I am so old..). Which gives me the idea of making smoothness an option, where people can chose their degree of smoothness over responsiveness.

For now I have tried to make it about as responsive as it was before the switch to ncurses.

**Comment by karlstav** [comment]
@CelestialWalrus I also found out that the gravity was much higher in the pre-ncurses version, tried to increase it in the modules branch, looks even snappier now.

**Comment by karlstav** [comment]
@CelestialWalrus can I close this off?

**Comment by CelestialWalrus** [comment]
@karlstav I'll test it soon (haven't yet). Hold on.

**Comment by karlstav** [comment]
@CelestialWalrus can I close this?

**Comment by CelestialWalrus** [comment]
@karlstav yeah.
