### ISSUE TITLE
Display mono output from highest to lowest frequencies

### ISSUE THREAD

**Issue by TrdNugget** [karlstav/cava#395]
**Disclaimer: I'm a GNU/Linux noob**

I have a dual monitor setup and have two instances of cava running on each, with a transparent emulator.
Basically, I'm trying to visualise a stereo signal over 2 monitors with the lowest frequencies in the center.
I've tried to simply span one instance of cava across the two monitors (with --geometry option from the terminator emulator) but it didn't let me go beyond one monitor.

I'm using Manjaro KDE Plasma

Sorry if I didn't give enough information/didn't phrase things understandably, I don't really have any experience with GitHub either

**Comment by karlstav** [comment]
@TrdNugget this a valid question, I guess the problem is that the leftmost instance also will have the lowest frequencies to the left. In order to get it mirrored you must use one instance across two monitors. I could make a config option for displaying the frequencies from higher to lower left to rigt. Then you would only need to make two configs that mirrored each other. 

For simplicity though, I think it would be easier to have one instances across two screens.

**Comment by TrdNugget** [comment]
@karlstav I'll try to get it to span across two screens then, thx for the quick reply!
Unfortunately the monitors have a different resolution so it won't be quite perfectly centered but oh well :)
