### ISSUE TITLE
Install fonts under the prefix directory

### ISSUE THREAD

**Issue by antiprism** [karlstav/cava#398]
Hi Karl

configure.ac has the font directory default to an absolute path
```DEFAULT_FONT_DIR="/usr/share/consolefonts"```
This means that it is not automatically installed under the prefix directory
```
... ./configure --prefix="/home/volumio/inst"  ...
...
make install-strip
...
/usr/bin/install -c -m 644 cava.psf '/usr/share/consolefonts'
/usr/bin/install: cannot remove '/usr/share/consolefonts/cava.psf': Permission denied
Makefile:764: recipe for target 'install-cava_font_DATA' failed
make[3]: *** [install-cava_font_DATA] Error 1
```
Some documentation about this: https://www.gnu.org/software/automake/manual/html_node/Hard_002dCoded-Install-Paths.html

I was able to install with FONT_DIR="/home/volumio/inst/usr/share/consolefonts"

Adrian.

**Comment by karlstav** [comment]
hi @antiprism 

this was a dirty hack I made because I could not find a good way for automake to install consolefonts (and I still can't)

setting
```
DEFAULT_FONT_DIR="${datarootdir}/consolefonts"
```

installs the font in `/usr/local/share/consolefonts/` and that does not work. It only works if it is in `/usr//share/consolefonts` (at least for Debian/Ubuntu).

I can make a "if prefix is not default", sort of conditional, but it seems like even more of a dirty hack. Or maybe not, or maybe I have missed something, I find it difficult to understand automake.

**Comment by karlstav** [comment]
this is only for using cava in a tty, it might be rather obscure. I could maybe leave the file and just drop a note about how to install it.

**Comment by antiprism** [comment]
Thanks for explaining the situation. It is easy enough to work around if it turns out that it is useful for a number of people to have the console font installed. I notice that I can set just set FONT_DIR=/tmp for a user install.

Please feel free to close the issue if you happy with the current behaviour.

**Comment by antiprism** [comment]
Hi Karl

I have just noticed your commits. I updated and tried a local install without setting FONT_DIR, and it now includes the font under the prefix directory. I didn't test the font, but your commit looks like a good approach.

Thanks

Adrian.

**Comment by karlstav** [comment]
I now use the FONT_DIR macro to locate the font at runtime, so it should work.
