### ISSUE TITLE
Improve autosens levels at start

### ISSUE THREAD

**Issue by antiprism** [karlstav/cava#404]
Hi Karl

The mpd_oled program has previously had instructions for configuring cava to use a FIFO provided by MPD, and has autosens enabled. The usual behaviour is that the spectrum bars initially overshoot the top of the screen, and then settle to something reasonable in a few seconds.

The audio players that mpd_oled runs on are now starting to support a copy of the audio using ALSA loopback. However, the audio levels sent to cava can change with the player volume, and when cava is configured to use this copy the spectrum bars can start very low, to the extent that it may not initially be clear that there are any bars. Autosens responds very slowly to this situation, and it may take 80-100 seconds before the spectrum bars are raised to their "stable" level.

I believe that this behaviour is reasonable in normal use, as music may have longer quiet sections and autosens shouldn't raise the levels too quickly.

Two suggestions for a possible solution:
- autosens could be a bit more aggressive at adjusting low levels shortly after cava starts
- an extra setting could set a starting value for audio levels so autosens could get the bars approximately right at the beginning for a user's usual volume setting

Adrian.

**Comment by karlstav** [comment]
hi @antiprism,

this is an issue that I struggled with in the past as well.

80-100 seconds sounds like a lot, are you sure about that? 

the problem here is that in some setups the volume can be limited in many places in the audio pipeline, if it is limited before cava captures the audio the sample values received would be relatively low. if they are kept at 100% until after cava captures the audio the sample values will be much much higher.




> autosens could be a bit more aggressive at adjusting low levels shortly after cava starts

this has been considered before (i actually thought it already had implemented it, had to check the git log). I will take a look at, should be trivial.



>   an extra setting could set a starting value for audio levels so autosens could get the bars approximately right at the beginning for a user's usual volume setting

this is actually more er less already the case:

https://github.com/karlstav/cava/blob/b0deff31f2d35ffb14e673280b73b479aba948f2/example_files/config#L18-L20

the comment is not entirely correct, it will have an effect even with autosens enabled, but just at launch before autosens stabilizes. It will be the initial sensitivity, just as you describe.

see if you can achieve the desired effect with increasing the sensitivity setting, then i can change the comment.

**Comment by antiprism** [comment]
Hi Karl

I did time the adjustment, but it is difficult to know the "end point". I just put on some ambient music, which had a fairly constant spectrum, and I timed it 90 seconds to reach the adjustment end point. The last part of the adjustment is relatively quick, so I think the time is reasonable to within a few seconds.

The sensitivity setting is working well: 400 took around 40 seconds, 1000 is fairly good, 10000 overshoots and corrects in a few seconds. It is definitely worth documenting as a feature!

I see you have pushed an update for the initial adjustment. I'll give it try.

Adrian.

**Comment by antiprism** [comment]
Hi Karl

I have just checked the update. The spectrum rises much more quickly, and overshoots slightly at around 5 seconds, before reducing and reaching the end point at around 7 seconds. Essentially, the spectrum is visibly pretty good after about 3-4 seconds. I then put the sensitivity to 10000 (!) and tested again, and the spectrum initially overshoots and then reduces to the end point in around 4 seconds.

The update appears to be working very well then. I'll close the issue!

Thanks for your help.

Adrian.
