### ISSUE TITLE
Question: How to get raw output every x seconds?

### ISSUE THREAD

**Issue by 1uk** [karlstav/cava#440]
Imagine this:

```
while(24fps) {
    render()
        { bar1, bar2, bar3, bar4 } = bash(cava --snapshot --bars 4);
        sprite.colorizeHsla(bar1, bar2, bar3, bar4);
    }
}
```
I know the code is just generic. I want to implement it in a c++ sdl2 game.
Is there the possibility to get a kind of *snapshot* from cava?
Is it fast enough to be in sync with the music?
Thanks for any help. Here is my video editing the colors of this game and making a video by editing.
https://youtu.be/9XymvWPsOk0

Thanks for any help.

**Comment by karlstav** [comment]
technically should be possible by running cava in the background and outputting to a fifo.

first create a fifo `mkfifo /tmp/cava`

set up cava with raw output and point to the fifo, in the `[output]`section:

```
method = raw
raw_target = /tmp/cava
data_format = ascii
```

just open the fifo in your application and parse the output there. you would probably need to use ascii output and then parse the output to find the bar and frame delimiters, since there will be no way to figure out when the frame ends and begins with the binary format.

I have never done anything like this, but I think it should work.

This is another motivation for the cavalib described in #260.
