### ISSUE TITLE
Use cava as simple non-realtime converter

### ISSUE THREAD

**Issue by antiprism** [karlstav/cava#443]
Hi

I would like to use cava to process suitably formatted PCM data and convert it to a spectrum data (raw) file. Ideally cava could be used as a filter, reading PCM from standard input and writing spectrum data to standard output.

I have experimented with PCM input from a file using 'method = fifo', without success, using file redirection and also with reading the same data from a  named pipe. Either the output is way too short, or cava keeps writing non-zero data forever. The problems may relate to cava expecting to receive input data at playback speed.

The reason for wanting this is that I am writing a script that uses spectrum data within natron (video and animation program) to make music visualization animations, and I just need an easy way of processing an audio file to get the spectrum data.

Adrian.

**Comment by karlstav** [comment]
hi @antiprism 

> The problems may relate to cava expecting to receive input data at playback speed.

this is correct, the fifo input will read as much as it can in a non-blocking fashion. 

the main problem with using cava for this is that the audio input runs in a separate thread, so you get problem with synchronization.

However, this is a perfect use case for the stuff I have been working on in the [cavalib branch](https://github.com/karlstav/cava/tree/cavalib).

you would have to write your own  application, but I think it can be done very simple. look in the [cavacore test app](https://github.com/karlstav/cava/blob/cavalib/cavacore_test.c). you can just replace the sinus waves I create there with the input from your file. You would have to iterate over your file and take n amounts of data into cava_execute a a time. The output can be written to a file and you can use the amount of data you have in each execute to time it.


I would be happy to help, because I want some testing on this branch before I merge it with master.

**Comment by antiprism** [comment]
Hi Karl

Thanks. I'll take a look!

Adrian.

**Comment by antiprism** [comment]
Hi Karl

I have attached a test program: [cava_filter01.zip](https://github.com/karlstav/cava/files/8408496/cava_filter01.zip)

For sample input I used the 440Hz tone from here
   https://www.mediacollege.com/audio/tone/download/
   https://www.mediacollege.com/audio/tone/files/440Hz_44100Hz_16bit_05sec.wav

Converted to PCM with
```
ffmpeg -i 440Hz_44100Hz_16bit_05sec.wav -f u16le -ar 44100 -acodec pcm_u16le u440.raw
```
The test program takes a framerate argument, e.g.
```
./cava_filter 20 < ../u440.raw
```
My code may not be correct. It produces output that seems reasonable, but has the following issues:
1. I am unsure what the output numbers represent. If I increase the number of bars from 10 to 20 the output numbers also increase.
2. There appears to be some early adaptation of values with autosens=0. I would like to be able to set a "level" value and have no adaptation at all.

Examples showing issues with 8 bars and 10 bars (adaptation, and increase in numbers)
8 bars:
```
samples_per_frame = 7350
reads_per_frame = 1
reads_per_frame_exact = 0.897217
input_len = 8192
output_len = 2048
16 	15 	0 	0 	475 	0 	0 	0 	
28 	28 	0 	0 	842 	0 	0 	0 	
22 	21 	0 	0 	1100 	0 	0 	0 	
17 	16 	0 	0 	1281 	0 	0 	0 	
13 	12 	0 	0 	1389 	0 	0 	0 	
10 	9 	0 	0 	1492 	0 	0 	0 	
7 	7 	0 	0 	1567 	0 	0 	0 	
6 	5 	0 	0 	1622 	0 	0 	0 	
4 	4 	0 	0 	1638 	0 	0 	0 	
3 	3 	0 	0 	1650 	0 	0 	0 	
2 	2 	0 	0 	1683 	0 	0 	0 	
2 	2 	0 	0 	1683 	0 	0 	0 	
1 	1 	0 	0 	1707 	0 	0 	0 	
1 	1 	0 	0 	1724 	0 	0 	0 	
1 	0 	0 	0 	1737 	0 	0 	0 	
0 	0 	0 	0 	1699 	0 	0 	0 	
0 	0 	0 	0 	1719 	0 	0 	0 	
0 	0 	0 	0 	1733 	0 	0 	0 	
0 	0 	0 	0 	1720 	0 	0 	0 	
0 	0 	0 	0 	1734 	0 	0 	0 	
0 	0 	0 	0 	1744 	0 	0 	0 	
0 	0 	0 	0 	1751 	0 	0 	0 	
0 	0 	0 	0 	1709 	0 	0 	0 	
0 	0 	0 	0 	1726 	0 	0 	0 	
0 	0 	0 	0 	1738 	0 	0 	0 	
0 	0 	0 	0 	1724 	0 	0 	0 	
0 	0 	0 	0 	1737 	0 	0 	0 	
0 	0 	0 	0 	1722 	0 	0 	0 	
0 	0 	0 	0 	1736 	0 	0 	0 	
0 	0 	0 	0 	1745 	0 	0 	0
```

10 bars:
```samples_per_frame = 7350
reads_per_frame = 1
reads_per_frame_exact = 0.897217
input_len = 8192
output_len = 2048
17 	19 	17 	0 	0 	641 	0 	0 	0 	0 	
31 	34 	30 	0 	0 	1135 	0 	0 	0 	0 	
24 	26 	23 	0 	0 	1447 	0 	0 	0 	0 	
18 	20 	17 	0 	0 	1700 	0 	0 	0 	0 	
14 	15 	13 	0 	0 	1885 	0 	0 	0 	0 	
11 	12 	10 	0 	0 	1996 	0 	0 	0 	0 	
8 	9 	8 	0 	0 	2101 	0 	0 	0 	0 	
6 	7 	6 	0 	0 	2178 	0 	0 	0 	0 	
5 	5 	4 	0 	0 	2211 	0 	0 	0 	0 	
3 	4 	3 	0 	0 	2235 	0 	0 	0 	0 	
3 	3 	2 	0 	0 	2276 	0 	0 	0 	0 	
2 	2 	2 	0 	0 	2282 	0 	0 	0 	0 	
1 	1 	1 	0 	0 	2311 	0 	0 	0 	0 	
1 	1 	1 	0 	0 	2308 	0 	0 	0 	0 	
1 	1 	1 	0 	0 	2329 	0 	0 	0 	0 	
0 	0 	0 	0 	0 	2321 	0 	0 	0 	0 	
0 	0 	0 	0 	0 	2339 	0 	0 	0 	0 	
0 	0 	0 	0 	0 	2329 	0 	0 	0 	0 	
0 	0 	0 	0 	0 	2345 	0 	0 	0 	0 	
0 	0 	0 	0 	0 	2332 	0 	0 	0 	0 	
0 	0 	0 	0 	0 	2324 	0 	0 	0 	0 	
0 	0 	0 	0 	0 	2341 	0 	0 	0 	0 	
0 	0 	0 	0 	0 	2330 	0 	0 	0 	0 	
0 	0 	0 	0 	0 	2345 	0 	0 	0 	0 	
0 	0 	0 	0 	0 	2357 	0 	0 	0 	0 	
0 	0 	0 	0 	0 	2318 	0 	0 	0 	0 	
0 	0 	0 	0 	0 	2337 	0 	0 	0 	0 	
0 	0 	0 	0 	0 	2350 	0 	0 	0 	0 	
0 	0 	0 	0 	0 	2313 	0 	0 	0 	0 	
0 	0 	0 	0 	0 	2333 	0 	0 	0 	0 	
```

Adrian.

**Comment by karlstav** [comment]
Hi Adrian.

thanks for the test report, I have already picked up a couple of bugs. First of all i had swapped the "treble buffer size" and "total buffer size" in my test app. it should be fixed now

the whole buffer naming is just confusing and should not be a client concern at all. The internal "bass" buffer in cava is 4x the treble buffer. this is because capturing the lowest frequencies requires using large buffers, but if we where reading and writing with buffers that big cava would become to slow to respond.

 this again leads to some of the second issue you have, it will take a couple of frames to fill up the internal buffer and therefore the first values might be a bit lower. maybe I can do something about that, but can't think of anything right now.

a third thing to clarify: the "framerate" given to the cava_plan is only used for smoothing. I can see the comments I have written in the header file has been garbled by the clang formatting, I tried to fix it now. I will try to remove the framerate config option it should not be necessary to set. the actual framerate output will be: `sample rate in audio file / samples in cava_in`. So for stereo you might actually try 1024 samples total per execution.

for 10 bars the lower cut off frequencies are:

```
50 	85 	144 	245 	416 	707 	1201 	2040 	3466 	5887 	MHz
```

so looks like our 440MHz signal somehow gets into the   707 - 1201 bucket. most likely a doubling caused by some confusion with the buffers or mono/stereo stuff

**Comment by antiprism** [comment]
Hi Karl

Sounds good. I'll wait for your update to cavacore and then update my program to follow the new documentation and example code, and see how it works out!

Regarding the adaptation of the initial output. If it is unavoidable then it will be a case of working around it if it turns out to be an issue in a visualisation. In this specific case, the non-zero values are very small relative to peak values and the peak value is pretty much attained within half a second and so this output could be fine in practice. Maybe a workaround, within my program, might be to play the first second of the audio in reverse at the beginning, and discard the bars for this.

Adrian.

**Comment by karlstav** [comment]
Already made the changes in the cavalib branch. So hopefully the test application should be more clearer to follow now.

**Comment by antiprism** [comment]
Hi Karl

My program is now working correctly, thank you! I switched from using uint16_t and u16le to using int16_t and s16le and the 440Hz value peak now matches the frequency cut off reported by cava. I'll post an updated version of my code after tidying it up.

Adrian.

**Comment by antiprism** [comment]
Hi Karl

Here is the updated code: [cava_filter02.zip](https://github.com/karlstav/cava/files/8417971/cava_filter02.zip)

Thanks for your help!

Adrian.

**Comment by antiprism** [comment]
I have converted cava_filter into a more usual command line program with options

   https://github.com/antiprism/cava_filter

Adrian.
