### ISSUE TITLE
Remove vim build dependency (through xxd)

### ISSUE THREAD

**Issue by baltitenger** [karlstav/cava#449]
**Is your feature request related to a problem? Please describe.**
Apparently the build (`autogen.sh`) uses `xxd` to embed the default config file in the executable, which is part of the `vim` distribution, and imo it's a ridiculous build-time dependency to have.

**Describe the solution you'd like**
Use some other method to embed the file (some `sed` hack, `ld` / `objcopy`, [incbin](https://github.com/graphitemaster/incbin)).

**Comment by karlstav** [comment]
xxd is just used to create a hexdump and header file of the example config. This is then included in the source. I did it like this to make sure the embedded config and example config is the same.

I thought it was pretty standard tool in all distributions, but I can see now that it is not. And in some cases it can only be installed as part of the vim package. Which I agree causes some strange looking build requirements.

I'll just check in the generated hex dump instead and create some routine for keeping it up to date with the example config.

**Comment by antiprism** [comment]
It would be useful to me, as I provide instructions for building cava, if non-optional dependency changes, like requiring xxd and libiniparser, could be announced ahead of time.

**Comment by ionenwks** [comment]
One option could be to create release tarballs with pre-generated files (rather than github's git dump), aka these could have the hardcoded version (rather than have to update them), autoconf files, and hexdumped header.

Not that it helps for people wanting to build from git, but over at Gentoo it'd let me drop the slow autoconf gen everytime sometime emerge the package, and vim-core dependency from the ebuild (not that I consider it a big deal).

**Comment by baltitenger** [comment]
I personally think the cleanest solution would be incbin, as it should work without any external dependencies and without any extra build config except on msvc.

**Comment by karlstav** [comment]
incbin looks cool, but why does this only produce an empty file?

```
diff --git a/config.c b/config.c
index 2c540fb..772c9f6 100644
--- a/config.c
+++ b/config.c
@@ -13,6 +13,9 @@
 #include <stdarg.h>
 #include <stdbool.h>
 #include <sys/stat.h>
+#include <incbin.h>
+
+INCTXT(ConfigFile, "example_files/config");
 
 double smoothDef[5] = {1, 1, 1, 1, 1};
 
@@ -422,7 +425,7 @@ bool load_config(char configPath[PATH_MAX], struct config_params *p, bool colors
             fseek(fp, 0, SEEK_END);
             if (ftell(fp) == 0) {
                 printf("config file is empty, creating default config file\n");
-                fwrite(example_files_config, example_files_config_len, sizeof(unsigned char), fp);
+                fwrite(gConfigFileEnd, gConfigFileSize, sizeof(char), fp);
             }
             fclose(fp);
         } else {
```

**Comment by baltitenger** [comment]
`gConfigFileEnd`? you probably want `gConfigFileData`. Also, INCTXT appends a null byte to your file.

**Comment by karlstav** [comment]
yea, I don't know how it became `End`, stupid mistake on my side. `gConfigFileData` works as expected 

@baltitenger do you know if I can just copy the header file into my project?

license looks pretty permissive

**Comment by baltitenger** [comment]
Not sure, I haven't used it in any "actual" projects, but I think it should be fine.

**Comment by karlstav** [comment]
@antiprism as @ionenwks points out, maybe better to use a specific release for what you are doing and not just cloning the master branch, especially since I do not have a development branch and just dump stuff right in the master branch.

@ionenwks, regarding making -Werror optional, sounds like a good idea and I can keep it enabled in the github actions at least. just open a new issue for it and I will look at it when I get time.

**Comment by antiprism** [comment]
I have previously temporarily switched to providing instructions to build cava from a specific commit when the build has not been working on a particular system, but I prefer tracking cava development, as it gives mpd_oled users an opportunity to support the cava project by reporting current cava issues (which I can then pass on).

Adrian.
