### ISSUE TITLE
Improved (sub-)bass resolution

### ISSUE THREAD

**Issue by bunder2015** [karlstav/cava#452]
Over in 289 I had noticed that bar resolution for bass and sub-bass frequencies seemed to be quite wide, and it was suggested that the buffer is too small, but increasing it could be detrimental to performance...  I still wanted to give it a try for giggles.

Initially I tried increasing `BUFFER_SIZE` to 2048, then 4096, then 8192.  Sadly that only seemed to make the bars really quiet, and they wouldn't peak past 10%.

I also tried increasing `FFTbassbufferSize` from `treble_buffer_size * 4` all the way up to 16.  This does seem to help, when playing single frequency tones there was less spillover into adjacent bars (4-5 bars to 2-3).  Not sure if increasing `FFTmidbufferSize` would also help, although I did bump that up from x2 to x8.

Haven't tested for performance, but it seems to run just as fine on my 7th gen Intel laptop.

Thanks again

**Comment by karlstav** [comment]
the bass buffer is 4096 at 44100 samples rate. in theory this should be able to pick up signals down to 10Hz, but I guess the resolution would be not that great.

To be precise the problem is that as the buffer increases we are also visualizing older and older parts of the signal, thus reducing the experience of the visualization itself.  So if you where trying treble_buffer_size * 16, that would mean 16384 samples at 44100, which is over 1/3 second! At that rate it would be hard to separate one beat from the next.

Just a doubling of the size seems to help a lot and the response is still good, will do some more testing and maybe push it.

**Comment by karlstav** [comment]
@bunder2015, I made some changes, should be a lot better now. I also fixed a bug in the xaxis labels. the center frequency calculation would not be correct anyway so now it uses lower cut off instead.

**Comment by bunder2015** [comment]
Hello, I gave it a shot and it does look better in most cases, [here's a comparison](https://drive.google.com/file/d/1RGQ5bLXxupUvvSXjzDqbMg5OoyWuEJqx/view).  There's still a few frequencies where it looks like too many bars are active but when some of the bars are only 5-10hz wide I'm probably splitting hairs. :smile: 

I'll close this up for now I suppose.  Thanks again for your help. :+1:
