### ISSUE TITLE
Raw output only accept even bars

### ISSUE THREAD

**Issue by hartontw** [karlstav/cava#467]
Odd numbers always print one less bar.
Even numbers work fine.

Is it expected or is a bug?
I'm not sure if it's related to https://github.com/karlstav/cava/issues/346

AUR [cava-git](https://aur.archlinux.org/packages/cava-git) (cava 0.8.2-20-g11e96cb)
I also compiled the master branch but is the same version at the moment.

Audio: pipewire with pipewire-pulse

Config:
```
[general]
framerate = 30
bars = 9

[output]
method = raw
data_format = ascii
ascii_max_range = 100

[input]
# default
```

Example output:
```
51;45;54;13;37;95;100;94;
51;45;58;13;37;100;100;96;
51;45;61;13;36;100;100;98;
51;45;63;14;38;100;100;98;
50;44;64;16;45;99;100;97;
49;43;64;20;56;100;100;96;
48;42;63;23;64;96;100;93;
46;40;61;25;71;96;100;89;
```

_Thanks for your awesome work._

**Comment by karlstav** [comment]
This is expected. The configuration here might be misleading. But since you have not specified otherwise the output defaults to stereo and the "bars" setting is total number of bars (left + right). If the setting is an even number it is simply decrease by one.

It might have been better if the setting was per output channel. But I fear it's too late to change now. Maybe I should throw an error message instead of decreasing the number in this case.

**Comment by hartontw** [comment]
Ok, I understand now. Make sense.

It's ok to me anyway.

Thanks for the clarification.
