### ISSUE TITLE
Enabling Gradient makes Cava not working  

### ISSUE THREAD

**Issue by PLAYERUNKNOWNHatsune01** [karlstav/cava#477]
Hello sir I have very dumb question since I try to search on any possibly fix on my simple problem but I can't find any fixes sir about the gradient. When I enable "gradient = 1" and start Cava this message always show up `Error loading config. Only 'ncurses' output method supports HTML colors. Please change the colours or the output method.
As of version 0.7.0 ncurses is no longer the default output method
Gradient color 1 is invalid. It must be HTML color of the form '#xxxxxx'.` . Disclaimer sir I'm not a developer and dumb one maybe the answer is right in front of me but can't see it. 

Here's the image sir: [https://ibb.co/nbK4MZz](url)

**Comment by karlstav** [comment]
this does look strange. 

how does your config file look and what is your version of cava?

**Comment by PLAYERUNKNOWNHatsune01** [comment]
I'm using 0.7.2 sir and my terminal is Alacritty and my OS is Fedora Linux sir

Here's the image sir

[![ff11.png](https://i.postimg.cc/59L41Zd9/ff11.png)](https://postimg.cc/bdYc9Vw4)

**Comment by karlstav** [comment]
as the error message says you need to change the `method` under `[output]` to ncurses.

however this has been fixed in later versions, but maybe you are using some packet manager to install cava that only has version 0.7.2.

don't know about the message about gradient color 1 being invalid, it looks valid. But try to do either:

a) change the `method` under `[output]` to ncurses., or
b) update cava

**Comment by PLAYERUNKNOWNHatsune01** [comment]
Thank you sir! It's working now. The (a) option worked for me
