### ISSUE TITLE
Pipewire support fails to crossbuild because of hardcoded include flags

### ISSUE THREAD

**Issue by tranzystorek-io** [karlstav/cava#519]
**Describe the bug**

When building Cava 0.9 for Void Linux, the cross-compile builds fail because of the hardcoded include flags: https://github.com/karlstav/cava/blob/83b4cda8177c780c7895ae67384c2679e84cc0d9/configure.ac#L111

i.e. for cross those are located under a platform-specific directory.

Not sure how hard it'd be to replace those checks with pkg-config, but it'd probably be more reliable.

**Additional context**

Build output on Void Linux CI: https://github.com/void-linux/void-packages/actions/runs/5830730727/job/15812721372?pr=45539

**Comment by karlstav** [comment]
this was a mistake from my part, was probably just mashing things in just to make it compile with the intent of doing it properly later.

should be ok now.

can you test it on your since @tranzystorek-io? I can make 0.9.1 release if it works ok, already squashed two pipewire bugs after releasing 0.9.0

**Comment by tranzystorek-io** [comment]
I should have this tested in a short while 👍

**Comment by tranzystorek-io** [comment]
Seems everything is working fine with that patch: https://github.com/void-linux/void-packages/pull/45539/checks

☺️

**Comment by tranzystorek-io** [comment]
Closing as it has been resolved
