### ISSUE TITLE
Keyboard commands not working

### ISSUE THREAD

**Issue by n6v26r** [karlstav/cava#536]
Issue with the cava-git aur package

No keyboard commands such as q for quit or r for reload work

**To reproduce:**
- Just install the cava-git aur package

**Desktop (please complete the following information):**

 - OS: Manjaro 
 - Version: latest version

**Terminal emulator**
- kitty
- latest version

**Comment by karlstav** [comment]
This id because I changed the default output mode from ncurses to noncurses. Noncurses does not support keyboard input. I didn't really think anyone was using the keyboard input, guess I was wrong. 

Noncurses did use to have keyboard input, but it was causing some issues so I disabled it. I will look into reimplementing it. If I cant, I will simply revert to using ncurses as default.

Until then simply change output mode to ncurses if you want keyboard. Remember you can always use ctrl+c for exit and 

pkill -USR1 cava

To reload

**Comment by karlstav** [comment]
@n6v26r, can you check with the latest commit that it works as expected?

**Comment by n6v26r** [comment]
Yep. Working just fine now. Wasn't a big issue anyway.
