### ISSUE TITLE
error opening stream: Operation not permitted

### ISSUE THREAD

**Issue by dokipen** [karlstav/cava#57]
Using Funtoo. I'm happy to list any relevant versions of different libs.

**Comment by CelestialWalrus** [comment]
Related to #55

**Comment by anko** [comment]
Which [method](https://github.com/karlstav/cava#capturing-audio) are you using to get audio into cava?

>     error opening stream: Operation not permitted

I also get that error if I tell cava to listen on the same ALSA output that's already directed to my speakers. If you've got a loopback set up and listen on that loopback, it should work.

[Here's the `.asoundrc`-config I'm using right now](http://unix.stackexchange.com/a/194631/16404) with cava is run as `cava -d hw:Loopback,1,0`.

This stuff can get confusing. Ask lots of questions and maybe we can think of a clear answer to them for future people! :)

**Comment by dokipen** [comment]
I'm using pulseaudio and created a loopback using the README instructions

**Comment by karlstav** [comment]
@dokipen could you give me the output of `arecord -l`

**Comment by hartwork** [comment]
@dokipen, since you mention Funtoo, there is an [ebuild in betagarden](http://gpo.zugaina.org/media-sound/cava).

**Comment by petervojtek** [comment]
hi,
I face the same issue with ubuntu 12.04.

here is my output of  arecord -l

**** List of CAPTURE Hardware Devices ****
card 0: Intel [HDA Intel], device 0: STAC92xx Analog [STAC92xx Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: Loopback [Loopback], device 0: Loopback PCM [Loopback PCM]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 2: Loopback [Loopback], device 1: Loopback PCM [Loopback PCM]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7

**Comment by karlstav** [comment]
@petervojtek your loopback device is card 2, cava defaults to using card 1 so you have to specify which card you should use. Try running cava with:

`./cava -d hw:2,1`

I defaulted cava to use hw:1,1 since I thought it would be the most common location of the loopback device. But since multiple users are affected by this issue maybe I should make the specification of interface a requirement when using alsa? Any thoughts? Not specifying any whould print an error message explaining how to find your loopback or input device and that you have to use the #1 device not the #0 on the loopback (I still don't know why this is).

**Comment by petervojtek** [comment]
Karl, thank you for quick reply. 
I guess it may be well enough to write this info into some Common Issues section.

**Comment by hartwork** [comment]
@karlstav
While we're at `-d hw:2,1`, I have been wondering what the `,1` is for and if that syntax is defined or explained anywhere.

>  I guess it may be well enough to write this info into some Common Issues section.

Personally, I vote for producing helpful instructions right from `cava` piggy-bagged with the error output.

**Comment by karlstav** [comment]
helpful instructions in the error messages is something that I have simply forgotten to do.

Also I realized now that you can specify the hardware device like this `hw:Loopback,1`, which of course should be the default device in cava.   

The ,1 is the device, one card can have more devices. the loopback card has two devices. It looks like there are two inputs and two outputs, but maybe ,0 only can be used as input and ,1 only as output. Because there are only one of each in the pulseaudio setup.

**Comment by karlstav** [comment]
closing this as error messages should now be more helpful, also hw:Loopback,1 is now default.
