### ISSUE TITLE
The current state of cava on Windows

### ISSUE THREAD

**Issue by ghost** [karlstav/cava#89]
Continuation of #34.

**Current progress:**
- Compiles under Cygwin
- Doesn't compile under MSYS/MinGW (pthread missing)
- ALSA will probably never work
- FIFO will have to be replaced with named pipes on Windows
- PulseAudio input works, but I couldn't get PulseAudio to get my Stereo Mix

Tested under Windows 10.

**Comment by nikp123** [comment]
This status is old, there is pthread for MinGW now, not sure if it works though.

I'll just use this screenshot as evidence:
![screen](https://cloud.githubusercontent.com/assets/4696350/22525398/4ad6835e-e8c7-11e6-97ac-4753ead472e1.png)

**Comment by nikp123** [comment]
[This](https://github.com/nikp123/cava/commit/7f075f6fe58fcba2e8472400a3e6c903bb090cb9) and [this](https://github.com/nikp123/cava/commit/13adc8ec1ffc97f2ec2a3fc635be6f428d101845) commit may be of interest. 
Good sides:
- Audio library > PortAudio (PulseAudio while it compiles, it never works)
- Display library > win32 window, terminal, and so on.
- Performance is on-par with Linux version
- Since PortAudio and Xlib exist, you could make a macOS-friendly version.

Bad sides:
- Compiles and runs ONLY under cygwin.
- In order to have a non-POSIX version of CAVA/minGW friendly version, I'll have to kill terminal support (aka. the letter 'C')

**Comment by quantum5** [comment]
Also for fun, I made Cava run on Windows Subsystem on Linux, sourcing audio from Windows with a helper program. See https://github.com/quantum5/winscap.

**Comment by karlstav** [comment]
i just spent a day mocking about with all sort of virtual network audio adapters in Windows trying to make Cava work in WSL. 

Then I stumble upon this old issue and find your amazing tool @quantum5 making the job a lot easier. 
![image](https://user-images.githubusercontent.com/6968928/109870873-e6790300-7c6a-11eb-81cf-398ea327605b.png)


 thanks!

**Comment by nikp123** [comment]
Anyway sorry to bother but I already have a working version of WASAPI audio streams in my fork.

However, even with that CAVA would fail to compile due to overreliance on POSIX/*NIX-y stuff. 

So my solution may not work for you.

**Comment by nikp123** [comment]
Although if you plan to run it within Cygwin or WSL (I think) it should work just fine

**Comment by karlstav** [comment]
with the quantem5s winscap there was no need for a wasapi input module. However this might have a place if I can do some further modularization as discussed in #402
