### ISSUE TITLE
More color support (256/rrggbb/true colors)

### ISSUE THREAD

**Issue by MCManuelLP** [karlstav/cava#91]
Until now the only way to change the available colors is to change the default terminal colors, is it possible to support more colors out of the box in the future?

**Comment by karlstav** [comment]
@MCManuelLP available colors will be limited to the colors supported in the terminal emulator. I guess 256 colors is possible like in [cli-visualizer](https://github.com/dpayne/cli-visualizer#256-colors). Looking at [this](https://gist.github.com/XVilka/8346728) I guess more colors are also possible. There is no specific plan yet, but I'll put it down in the todo list.

**Comment by hashhar** [comment]
I think you should add a configuration option called 'truecolor' which can be an integer from 0 to 255 which will be simply passed to `ncurses`. Currently you are reading from the config file and using a string compare and assign values to `bcolor` and `color` accordingly.

I propose the following:
1. Add a new option called `BG Truecolor` and `FG Truecolor` which will be an `int` (a `char` really) from 0 to 255.
2. Ignore the `bcolor` and `color` if either of the above are set and simply set `bcolor=BG Truecolor` and `color=FG Truecolor`.
3. Marvel at rainbows!!! :tada: 

If you want I can submit a pull within the next few days after properly testing that nothing else breaks because of such a change.

**PS: Thanks a lot for such a great tool @karlstav.**

**Comment by karlstav** [comment]
@hashhar yes indeed please do!

But I suggest a simple "custom" instead of "BG Truecolor"/"FG Truecolor". and then you whould need six options: red, green and blue for both foreground and background. Which must be an int from 0-1000 each.  Why 1000? because that's how the [color redefinition](http://tldp.org/HOWTO/NCURSES-Programming-HOWTO/color.html#CHANGECOLORDEFS) in ncurses works. Off course we don't have to use 0-1000, but I don't see why not.

Note: we need to make a handle for terminals who can't change the color definition.

**Comment by hashhar** [comment]
@karlstav Sure I'll start working on it.

**Comment by hashhar** [comment]
@karlstav Hey, I managed to add a config setting but there's an issue I would like to discuss with you.

**NOTE: I'm currently only looking to get the feature going as a proof of concept and will then streamline the config and add tests.**

I am currently designing the patch as follows.

1. A new config. `customColor` and `customBColor`. Both have to be valid html hex colour codes.
2. Read it in and validate the values. Exit after errors if the values are not valid.
3. Ignore `color` and `bcolor` if the above values are valid. Otherwise, use `color` and `bcolor`.
4. Set `col` and `bgcol` and pass control to `int init_terminal_ncurses(int col, int bgcol)`.

So this is where the problem is.
I would like to call the `init_color()` in `terminal_ncurses.c` to keep the structure logical. ie the same thing that you do now.

But the `col` and `bgcol` have to also be able to encode the `customColor` and `customBColor`.
So I was thinking about something like extracting the RGB values into three separate integers and then set `col` and `bgcol` to a value `RGB`. ie. `#f0f` would set `col = 909` and the `init_terminal_ncurses` will adjust for that. 

**BENEFITS:**
- Same functions as before.
- Code path is not changed.

**DRAWBACKS:**
- Cumbersome. May be unreadable for future contributors.

So I was thinking to maybe change the `init` function to `int init_terminal_ncurses(int col, int bgcol, long customcol, long custombgcol)` and set `col=bgcol=0` if using custom colours or the other way around.

A simpler way would be to change it to `int init_terminal_ncurses(long col, long bgcol, [int mode])`. Now we can simply check the values of `col` and `bgcol` to decide or use the `mode` flag to decide.

What would you like.

**Comment by hashhar** [comment]
@karlstav Hey, I managed to add a config setting but there's an issue I would like to discuss with you.

**NOTE: I'm currently only looking to get the feature going as a proof of concept and will then streamline the config and add tests.**

I am currently designing the patch as follows.

1. A new config. `customColor` and `customBColor`. Both have to be valid html hex colour codes.
2. Read it in and validate the values. Exit after errors if the values are not valid.
3. Ignore `color` and `bcolor` if the above values are valid. Otherwise, use `color` and `bcolor`.
4. Set `col` and `bgcol` and pass control to `int init_terminal_ncurses(int col, int bgcol)`.

So this is where the problem is.
I would like to call the `init_color()` in `terminal_ncurses.c` to keep the structure logical. ie the same thing that you do now.

But the `col` and `bgcol` have to also be able to encode the `customColor` and `customBColor`.
So I was thinking about something like extracting the RGB values into three separate integers and then set `col` and `bgcol` to a value `RGB`. ie. `#f0f` would set `col = 909` and the `init_terminal_ncurses` will adjust for that. 

**BENEFITS:**
- Same functions as before.
- Code path is not changed.

**DRAWBACKS:**
- Cumbersome. May be unreadable for future contributors.

So I was thinking to maybe change the `init` function to `int init_terminal_ncurses(int col, int bgcol, long customcol, long custombgcol)` and set `col=bgcol=0` if using custom colours or the other way around.

A simpler way would be to change it to `int init_terminal_ncurses(long col, long bgcol, [int mode])`. Now we can simply check the values of `col` and `bgcol` to decide or use the `mode` flag to decide.

What would you like.

**Comment by hashhar** [comment]
@karlstav I got it working. But how do I reset the colors back to the terminal defaults after redefining them using `init_color`. I am currently redefining COLOR_BLACK and COLOR_WHITE and using them to generate the `COLOR_PAIR` to render. It renders really fine.

![2016-10-26_22-36-12_1366x768](https://cloud.githubusercontent.com/assets/10473142/19736405/b5f1c6be-9bcc-11e6-92b2-1cd471af402f.png)

**Comment by karlstav** [comment]
@hashhar i have a suggestion, why not just pass col and bgcol as strings to the function instead of int. Also I think you can use true colors (24-bit) in ncurses? (not 100% sure). So the user can just set 'foreground' or 'background' in the config to either the predefined values "black", "green"... OR set it to something like #3C77A4.

The validation will be moved to inside the function. If it starts with a '#' and is a valid six digit hex code we will use init_color to change the color.

**Comment by hashhar** [comment]
@karlstav I decided to read more documentation and what you are saying is correct. I'm changing the code to simply read a `#xxxxxx` style value from config and pass it as a string. I think I'll get it ready by the weekend. With error handling and all.

**Comment by hashhar** [comment]
@karlstav I got it working exactly as you said. But there's a issue.

1. Redefining messes us color scheme:
Since I am redefining colours, there must be a way to restore the original terminal palette on exit.  
As far as I know, `ncurses` doesn't provide a way to do that. It has a function to read values of a color definition.  
There is a hacky way using some terminal sequences but they are different for different terminals and are not well documented and some don't even have them.
**So one way to solve this is to write those values someplace (`/tmp/maybe`) and reset the color redifinitions when exiting.** But this has the issue that if the program crashes, the colors won't be reset. They would have to close and open a new terminal to get original colors back.

2. Non-curses mode:
**Can the non-curses mode show 256 colors? How?** I tried reading the `init_terminal_noncurses()` but couldn't understand.
Should we tell users that only ncurses mode will support 256 colors?

**Comment by karlstav** [comment]
@hashhar I am super overloaded with work until next thursday, I will look at the PR when I can. But first:



> As far as I know, ncurses doesn't provide a way to do that. It has a function to read values of a color definition.

If we can read the values before we change them, can we then just change it back with the cleanup function at exit? why do we have to store it in a file?



>  if the program crashes, the colors won't be reset.

if it does a lot of other terminal settings like `echo off` already f's upp the terminal pretty bad.



> Should we tell users that only ncurses mode will support 256 colors?

yes, and are we have not talking about 24-bit colours?

**Comment by hashhar** [comment]
> If we can read the values before we change them, can we then just change it back with the cleanup
> function at exit? why do we have to store it in a file?

I tried that but somehow the values are not persisted. I'll try to step through the code. Honestly I didn't spend much time yet on getting it to work.

The number of colours solely depends on the terminal support. Most terminals max out at 256. I don't know if that's 24-bit. I think that's 16-bit. Although you can specify any colour you want using HTML, the terminal will render it to the nearest matching colour available in the palette.

**Comment by karlstav** [comment]
I see,

256 is 8 bit. 2^8=256

**Comment by karlstav** [comment]
@hashhar I added some work on the morecolor brach,

first of all the code was broken because of what i think was the beginning of a check to see if the terminal supported color redefinition:

```c
	int has_colors = 0;
	if (has_colors() == TRUE) {
		has_colors = 1;
	}
```

i just commented it out for now, leaving `has_colors = 1`.

I also added a reset of the color definitions, just by setting them back to the ncurses default (1000,0,0 for red and 0,1000,0 for green) 

```
init_color(1, 1000, 0, 0);
init_color(2, 0, 1000, 0);
```

BTW we will have a problem if someone is crazy enough to have 'red' as there defined background color and then try to use a custom foreground color.

I also fixed color cycling when no custom color is defined by passing the old `col` and `bgcol` ints to the init function, as long as no custom color is defined those are used instead.

I hope this didn't "break" with your work in any way. Feel free to modify my contributions if you see fit.

**Comment by hashhar** [comment]
I didn't understand the part about red background breaking code. I think everything else is good.

I will check out the code and try to fix the color check (`has_colors()`).

Does resetting the colours to default fix the issue that we had which could only be fixed by opening a new terminal?

**Comment by karlstav** [comment]
> I didn't understand the part about red background breaking code.

you can test it yourself, define the background as `red` and try to define a custom foreground color. The problem is that your code changes the terminal's definition of `red`. So background and foreground will in that case be the same. (For custom background it changes the definition of green).  However I can't think of another way to do this.


> Does resetting the colours to default fix the issue that we had which could only be fixed by opening a new terminal?

`init_color(1 ...` changes the definition of red and `init_color(2 ...` changes the definition of green, so resetting them to the default should solve the issue of terminal color being redefined permanently, or perhaps it will only solve it for terminals wich are already using the default colors.

**Comment by hashhar** [comment]
I understand. Yes, there is no way to define personal colours. In some cases I was able to define colours at indices larger than 7 so that it does not mess up the default colours but it still is hit and miss.

I will ask around about how other people do it.
Got it.

I'll try to get back to you within two or three days.

**Comment by karlstav** [comment]
according [this](http://tldp.org/HOWTO/NCURSES-Programming-HOWTO/color.html#CHANGECOLORDEFS) there are only seven colors. But maybe there is another way. We could also manually define some other color to red if someone wants to have red as background while defining a custom foreground color (although I think this is an unlikely scenario)

**Comment by karlstav** [comment]
now i see what you where trying to do with `has_colors()` function. I think I was able to fix it, but I don't know of any terminal that does not support color manipulation, so I can't test t.

**Comment by karlstav** [comment]
@hashhar just pushed this to master, lets hope there's not to many bugs. We'll find out soon enough.
 
Thanks for all the work!

**Comment by karlstav** [comment]
closing this now as it looks good. thanks for all the help.

**Comment by hashhar** [comment]
@karlstav Thanks. It was a cool learning experience for me using ncurses. I'll try and look into some other issues when I have the time.
